#pragma once

// CryMP: true for C1 FMOD (0.4.7.23) and false for Warhead/Wars FMOD (0.4.14.3)
extern bool g_hasC1Fmod;

#ifdef _MSC_VER
#define F_API __stdcall
#define F_CALLBACK __stdcall
#else
#define F_API
#define F_CALLBACK
#endif

struct FMOD_SYSTEM;
struct FMOD_SOUND;
struct FMOD_CHANNEL;
struct FMOD_CHANNELGROUP;
struct FMOD_SOUNDGROUP;
struct FMOD_REVERB;
struct FMOD_DSP;
struct FMOD_DSPCONNECTION;
struct FMOD_GEOMETRY;
struct FMOD_SYNCPOINT;

using FMOD_BOOL = int;
using FMOD_MODE = unsigned int;
using FMOD_TIMEUNIT = unsigned int;
using FMOD_INITFLAGS = unsigned int;
using FMOD_CAPS = unsigned int;
using FMOD_DEBUGLEVEL = unsigned int;
using FMOD_MEMORY_TYPE = unsigned int;

struct FMOD_VECTOR
{
	float x;
	float y;
	float z;
};

struct FMOD_GUID
{
	unsigned int Data1;
	unsigned short Data2;
	unsigned short Data3;
	unsigned char Data4[8];
};

enum FMOD_RESULT
{
	FMOD_OK,
	FMOD_ERR_ALREADYLOCKED,
	FMOD_ERR_BADCOMMAND,
	FMOD_ERR_CDDA_DRIVERS,
	FMOD_ERR_CDDA_INIT,
	FMOD_ERR_CDDA_INVALID_DEVICE,
	FMOD_ERR_CDDA_NOAUDIO,
	FMOD_ERR_CDDA_NODEVICES,
	FMOD_ERR_CDDA_NODISC,
	FMOD_ERR_CDDA_READ,
	FMOD_ERR_CHANNEL_ALLOC,
	FMOD_ERR_CHANNEL_STOLEN,
	FMOD_ERR_COM,
	FMOD_ERR_DMA,
	FMOD_ERR_DSP_CONNECTION,
	FMOD_ERR_DSP_FORMAT,
	FMOD_ERR_DSP_NOTFOUND,
	FMOD_ERR_DSP_RUNNING,
	FMOD_ERR_DSP_TOOMANYCONNECTIONS,
	FMOD_ERR_FILE_BAD,
	FMOD_ERR_FILE_COULDNOTSEEK,
	FMOD_ERR_FILE_DISKEJECTED,
	FMOD_ERR_FILE_EOF,
	FMOD_ERR_FILE_NOTFOUND,
	FMOD_ERR_FILE_UNWANTED,
	FMOD_ERR_FORMAT,
	FMOD_ERR_HTTP,
	FMOD_ERR_HTTP_ACCESS,
	FMOD_ERR_HTTP_PROXY_AUTH,
	FMOD_ERR_HTTP_SERVER_ERROR,
	FMOD_ERR_HTTP_TIMEOUT,
	FMOD_ERR_INITIALIZATION,
	FMOD_ERR_INITIALIZED,
	FMOD_ERR_INTERNAL,
	FMOD_ERR_INVALID_ADDRESS,
	FMOD_ERR_INVALID_FLOAT,
	FMOD_ERR_INVALID_HANDLE,
	FMOD_ERR_INVALID_PARAM,
	FMOD_ERR_INVALID_SPEAKER,
	FMOD_ERR_INVALID_VECTOR,
	FMOD_ERR_IRX,
	FMOD_ERR_MAXAUDIBLE,
	FMOD_ERR_MEMORY,
	FMOD_ERR_MEMORY_CANTPOINT,
	FMOD_ERR_MEMORY_IOP,
	FMOD_ERR_MEMORY_SRAM,
	FMOD_ERR_NEEDS2D,
	FMOD_ERR_NEEDS3D,
	FMOD_ERR_NEEDSHARDWARE,
	FMOD_ERR_NEEDSSOFTWARE,
	FMOD_ERR_NET_CONNECT,
	FMOD_ERR_NET_SOCKET_ERROR,
	FMOD_ERR_NET_URL,
	FMOD_ERR_NET_WOULD_BLOCK,
	FMOD_ERR_NOTREADY,
	FMOD_ERR_OUTPUT_ALLOCATED,
	FMOD_ERR_OUTPUT_CREATEBUFFER,
	FMOD_ERR_OUTPUT_DRIVERCALL,
	FMOD_ERR_OUTPUT_ENUMERATION,
	FMOD_ERR_OUTPUT_FORMAT,
	FMOD_ERR_OUTPUT_INIT,
	FMOD_ERR_OUTPUT_NOHARDWARE,
	FMOD_ERR_OUTPUT_NOSOFTWARE,
	FMOD_ERR_PAN,
	FMOD_ERR_PLUGIN,
	FMOD_ERR_PLUGIN_INSTANCES,
	FMOD_ERR_PLUGIN_MISSING,
	FMOD_ERR_PLUGIN_RESOURCE,
	FMOD_ERR_RECORD,
	FMOD_ERR_REVERB_INSTANCE,
	FMOD_ERR_SUBSOUND_ALLOCATED,
	FMOD_ERR_SUBSOUND_CANTMOVE,
	FMOD_ERR_SUBSOUND_MODE,
	FMOD_ERR_SUBSOUNDS,
	FMOD_ERR_TAGNOTFOUND,
	FMOD_ERR_TOOMANYCHANNELS,
	FMOD_ERR_UNIMPLEMENTED,
	FMOD_ERR_UNINITIALIZED,
	FMOD_ERR_UNSUPPORTED,
	FMOD_ERR_UPDATE,
	FMOD_ERR_VERSION,

	FMOD_ERR_EVENT_FAILED,
	FMOD_ERR_EVENT_INFOONLY,
	FMOD_ERR_EVENT_INTERNAL,
	FMOD_ERR_EVENT_MAXSTREAMS,
	FMOD_ERR_EVENT_MISMATCH,
	FMOD_ERR_EVENT_NAMECONFLICT,
	FMOD_ERR_EVENT_NOTFOUND,

	FMOD_RESULT_FORCEINT = 65536,
};

enum FMOD_OUTPUTTYPE
{
	FMOD_OUTPUTTYPE_AUTODETECT,

	FMOD_OUTPUTTYPE_UNKNOWN,
	FMOD_OUTPUTTYPE_NOSOUND,
	FMOD_OUTPUTTYPE_WAVWRITER,
	FMOD_OUTPUTTYPE_NOSOUND_NRT,
	FMOD_OUTPUTTYPE_WAVWRITER_NRT,

	FMOD_OUTPUTTYPE_DSOUND,
	FMOD_OUTPUTTYPE_WINMM,
	FMOD_OUTPUTTYPE_OPENAL,
	FMOD_OUTPUTTYPE_WASAPI,
	FMOD_OUTPUTTYPE_ASIO,
	FMOD_OUTPUTTYPE_OSS,
	FMOD_OUTPUTTYPE_ALSA,
	FMOD_OUTPUTTYPE_ESD,
	FMOD_OUTPUTTYPE_SOUNDMANAGER,
	FMOD_OUTPUTTYPE_COREAUDIO,
	FMOD_OUTPUTTYPE_XBOX,
	FMOD_OUTPUTTYPE_PS2,
	FMOD_OUTPUTTYPE_PS3,
	FMOD_OUTPUTTYPE_GC,
	FMOD_OUTPUTTYPE_XBOX360,
	FMOD_OUTPUTTYPE_PSP,
	FMOD_OUTPUTTYPE_WII,

	FMOD_OUTPUTTYPE_MAX,
	FMOD_OUTPUTTYPE_FORCEINT = 65536,
};

#define FMOD_CAPS_NONE 0x00000000
#define FMOD_CAPS_HARDWARE 0x00000001
#define FMOD_CAPS_HARDWARE_EMULATED 0x00000002
#define FMOD_CAPS_OUTPUT_MULTICHANNEL 0x00000004
#define FMOD_CAPS_OUTPUT_FORMAT_PCM8 0x00000008
#define FMOD_CAPS_OUTPUT_FORMAT_PCM16 0x00000010
#define FMOD_CAPS_OUTPUT_FORMAT_PCM24 0x00000020
#define FMOD_CAPS_OUTPUT_FORMAT_PCM32 0x00000040
#define FMOD_CAPS_OUTPUT_FORMAT_PCMFLOAT 0x00000080
#define FMOD_CAPS_REVERB_EAX2 0x00000100
#define FMOD_CAPS_REVERB_EAX3 0x00000200
#define FMOD_CAPS_REVERB_EAX4 0x00000400
#define FMOD_CAPS_REVERB_EAX5 0x00000800
#define FMOD_CAPS_REVERB_I3DL2 0x00001000
#define FMOD_CAPS_REVERB_LIMITED 0x00002000

#define FMOD_DEBUG_LEVEL_NONE 0x00000000
#define FMOD_DEBUG_LEVEL_LOG 0x00000001
#define FMOD_DEBUG_LEVEL_ERROR 0x00000002
#define FMOD_DEBUG_LEVEL_WARNING 0x00000004
#define FMOD_DEBUG_LEVEL_HINT 0x00000008
#define FMOD_DEBUG_LEVEL_ALL 0x000000FF
#define FMOD_DEBUG_TYPE_MEMORY 0x00000100
#define FMOD_DEBUG_TYPE_THREAD 0x00000200
#define FMOD_DEBUG_TYPE_FILE 0x00000400
#define FMOD_DEBUG_TYPE_NET 0x00000800
#define FMOD_DEBUG_TYPE_EVENT 0x00001000
#define FMOD_DEBUG_TYPE_ALL 0x0000FFFF
#define FMOD_DEBUG_DISPLAY_TIMESTAMPS 0x01000000
#define FMOD_DEBUG_DISPLAY_LINENUMBERS 0x02000000
#define FMOD_DEBUG_DISPLAY_COMPRESS 0x04000000
#define FMOD_DEBUG_DISPLAY_ALL 0x0F000000
#define FMOD_DEBUG_ALL 0xFFFFFFFF

#define FMOD_MEMORY_NORMAL 0x00000000
#define FMOD_MEMORY_XBOX360_PHYSICAL 0x00100000
#define FMOD_MEMORY_PERSISTENT 0x00200000

enum FMOD_SPEAKERMODE
{
	FMOD_SPEAKERMODE_RAW,
	FMOD_SPEAKERMODE_MONO,
	FMOD_SPEAKERMODE_STEREO,
	FMOD_SPEAKERMODE_QUAD,
	FMOD_SPEAKERMODE_SURROUND,
	FMOD_SPEAKERMODE_5POINT1,
	FMOD_SPEAKERMODE_7POINT1,
	FMOD_SPEAKERMODE_PROLOGIC,

	FMOD_SPEAKERMODE_MAX,
	FMOD_SPEAKERMODE_FORCEINT = 65536,
};

enum FMOD_SPEAKER
{
	FMOD_SPEAKER_FRONT_LEFT,
	FMOD_SPEAKER_FRONT_RIGHT,
	FMOD_SPEAKER_FRONT_CENTER,
	FMOD_SPEAKER_LOW_FREQUENCY,
	FMOD_SPEAKER_BACK_LEFT,
	FMOD_SPEAKER_BACK_RIGHT,
	FMOD_SPEAKER_SIDE_LEFT,
	FMOD_SPEAKER_SIDE_RIGHT,

	FMOD_SPEAKER_MAX,
	FMOD_SPEAKER_MONO = FMOD_SPEAKER_FRONT_LEFT,
	FMOD_SPEAKER_NULL = FMOD_SPEAKER_MAX,
	FMOD_SPEAKER_SBL = FMOD_SPEAKER_SIDE_LEFT,
	FMOD_SPEAKER_SBR = FMOD_SPEAKER_SIDE_RIGHT,
	FMOD_SPEAKER_FORCEINT = 65536,
};

enum FMOD_PLUGINTYPE
{
	FMOD_PLUGINTYPE_OUTPUT,
	FMOD_PLUGINTYPE_CODEC,
	FMOD_PLUGINTYPE_DSP,

	FMOD_PLUGINTYPE_MAX,
	FMOD_PLUGINTYPE_FORCEINT = 65536,
};

#define FMOD_INIT_NORMAL 0x00000000
#define FMOD_INIT_STREAM_FROM_UPDATE 0x00000001
#define FMOD_INIT_3D_RIGHTHANDED 0x00000002
#define FMOD_INIT_SOFTWARE_DISABLE 0x00000004
#define FMOD_INIT_SOFTWARE_OCCLUSION 0x00000008
#define FMOD_INIT_SOFTWARE_HRTF 0x00000010
#define FMOD_INIT_ENABLE_PROFILE 0x00000020
#define FMOD_INIT_VOL0_BECOMES_VIRTUAL 0x00000080
#define FMOD_INIT_WASAPI_EXCLUSIVE 0x00000100
#define FMOD_INIT_DSOUND_HRTFNONE 0x00000200
#define FMOD_INIT_DSOUND_HRTFLIGHT 0x00000400
#define FMOD_INIT_DSOUND_HRTFFULL 0x00000800
#define FMOD_INIT_PS2_DISABLECORE0REVERB 0x00010000
#define FMOD_INIT_PS2_DISABLECORE1REVERB 0x00020000
#define FMOD_INIT_PS2_DONTUSESCRATCHPAD 0x00040000
#define FMOD_INIT_PS2_SWAPDMACHANNELS 0x00080000
#define FMOD_INIT_PS3_PREFERDTS 0x00800000
#define FMOD_INIT_PS3_FORCE2CHLPCM 0x01000000
#define FMOD_INIT_XBOX_REMOVEHEADROOM 0x00100000
#define FMOD_INIT_360_MUSICMUTENOTPAUSE 0x00200000
#define FMOD_INIT_SYNCMIXERWITHUPDATE 0x00400000

enum FMOD_SOUND_TYPE
{
	FMOD_SOUND_TYPE_UNKNOWN,
	FMOD_SOUND_TYPE_AAC,
	FMOD_SOUND_TYPE_AIFF,
	FMOD_SOUND_TYPE_ASF,
	FMOD_SOUND_TYPE_AT3,
	FMOD_SOUND_TYPE_CDDA,
	FMOD_SOUND_TYPE_DLS,
	FMOD_SOUND_TYPE_FLAC,
	FMOD_SOUND_TYPE_FSB,
	FMOD_SOUND_TYPE_GCADPCM,
	FMOD_SOUND_TYPE_IT,
	FMOD_SOUND_TYPE_MIDI,
	FMOD_SOUND_TYPE_MOD,
	FMOD_SOUND_TYPE_MPEG,
	FMOD_SOUND_TYPE_OGGVORBIS,
	FMOD_SOUND_TYPE_PLAYLIST,
	FMOD_SOUND_TYPE_RAW,
	FMOD_SOUND_TYPE_S3M,
	FMOD_SOUND_TYPE_SF2,
	FMOD_SOUND_TYPE_USER,
	FMOD_SOUND_TYPE_WAV,
	FMOD_SOUND_TYPE_XM,
	FMOD_SOUND_TYPE_XMA,
	FMOD_SOUND_TYPE_VAG,

	FMOD_SOUND_TYPE_MAX,
	FMOD_SOUND_TYPE_FORCEINT = 65536,
};

enum FMOD_SOUND_FORMAT
{
	FMOD_SOUND_FORMAT_NONE,
	FMOD_SOUND_FORMAT_PCM8,
	FMOD_SOUND_FORMAT_PCM16,
	FMOD_SOUND_FORMAT_PCM24,
	FMOD_SOUND_FORMAT_PCM32,
	FMOD_SOUND_FORMAT_PCMFLOAT,
	FMOD_SOUND_FORMAT_GCADPCM,
	FMOD_SOUND_FORMAT_IMAADPCM,
	FMOD_SOUND_FORMAT_VAG,
	FMOD_SOUND_FORMAT_XMA,
	FMOD_SOUND_FORMAT_MPEG,

	FMOD_SOUND_FORMAT_MAX,
	FMOD_SOUND_FORMAT_FORCEINT = 65536,
};

#define FMOD_DEFAULT 0x00000000
#define FMOD_LOOP_OFF 0x00000001
#define FMOD_LOOP_NORMAL 0x00000002
#define FMOD_LOOP_BIDI 0x00000004
#define FMOD_2D 0x00000008
#define FMOD_3D 0x00000010
#define FMOD_HARDWARE 0x00000020
#define FMOD_SOFTWARE 0x00000040
#define FMOD_CREATESTREAM 0x00000080
#define FMOD_CREATESAMPLE 0x00000100
#define FMOD_CREATECOMPRESSEDSAMPLE 0x00000200
#define FMOD_OPENUSER 0x00000400
#define FMOD_OPENMEMORY 0x00000800
#define FMOD_OPENMEMORY_POINT 0x10000000
#define FMOD_OPENRAW 0x00001000
#define FMOD_OPENONLY 0x00002000
#define FMOD_ACCURATETIME 0x00004000
#define FMOD_MPEGSEARCH 0x00008000
#define FMOD_NONBLOCKING 0x00010000
#define FMOD_UNIQUE 0x00020000
#define FMOD_3D_HEADRELATIVE 0x00040000
#define FMOD_3D_WORLDRELATIVE 0x00080000
#define FMOD_3D_LOGROLLOFF 0x00100000
#define FMOD_3D_LINEARROLLOFF 0x00200000
#define FMOD_3D_CUSTOMROLLOFF 0x04000000
#define FMOD_3D_IGNOREGEOMETRY 0x40000000
#define FMOD_CDDA_FORCEASPI 0x00400000
#define FMOD_CDDA_JITTERCORRECT 0x00800000
#define FMOD_UNICODE 0x01000000
#define FMOD_IGNORETAGS 0x02000000
#define FMOD_LOWMEM 0x08000000
#define FMOD_LOADSECONDARYRAM 0x20000000
#define FMOD_VIRTUAL_PLAYFROMSTART 0x80000000

enum FMOD_OPENSTATE
{
	FMOD_OPENSTATE_READY = 0,
	FMOD_OPENSTATE_LOADING,
	FMOD_OPENSTATE_ERROR,
	FMOD_OPENSTATE_CONNECTING,
	FMOD_OPENSTATE_BUFFERING,
	FMOD_OPENSTATE_SEEKING,
	FMOD_OPENSTATE_STREAMING,

	FMOD_OPENSTATE_MAX,
	FMOD_OPENSTATE_FORCEINT = 65536,
};

enum FMOD_SOUNDGROUP_BEHAVIOR
{
	FMOD_SOUNDGROUP_BEHAVIOR_FAIL,
	FMOD_SOUNDGROUP_BEHAVIOR_MUTE,
	FMOD_SOUNDGROUP_BEHAVIOR_STEALLOWEST,

	FMOD_SOUNDGROUP_BEHAVIOR_MAX,
	FMOD_SOUNDGROUP_BEHAVIOR_FORCEINT = 65536,
};

enum FMOD_CHANNEL_CALLBACKTYPE
{
	FMOD_CHANNEL_CALLBACKTYPE_END,
	FMOD_CHANNEL_CALLBACKTYPE_VIRTUALVOICE,
	FMOD_CHANNEL_CALLBACKTYPE_SYNCPOINT,

	FMOD_CHANNEL_CALLBACKTYPE_MAX,
	FMOD_CHANNEL_CALLBACKTYPE_FORCEINT = 65536,
};

enum FMOD_SYSTEM_CALLBACKTYPE
{
	FMOD_SYSTEM_CALLBACKTYPE_DEVICELISTCHANGED,
	FMOD_SYSTEM_CALLBACKTYPE_MEMORYALLOCATIONFAILED,
	FMOD_SYSTEM_CALLBACKTYPE_THREADCREATED,

	FMOD_SYSTEM_CALLBACKTYPE_MAX,
	FMOD_SYSTEM_CALLBACKTYPE_FORCEINT = 65536,
};

using FMOD_SYSTEM_CALLBACK = FMOD_RESULT(F_CALLBACK*)(FMOD_SYSTEM* system, FMOD_SYSTEM_CALLBACKTYPE type,
                                                      void* commanddata1, void* commanddata2);

using FMOD_CHANNEL_CALLBACK = FMOD_RESULT(F_CALLBACK*)(FMOD_CHANNEL* channel, FMOD_CHANNEL_CALLBACKTYPE type,
                                                       int command, unsigned int commanddata1,
                                                       unsigned int commanddata2);

using FMOD_SOUND_NONBLOCKCALLBACK = FMOD_RESULT(F_CALLBACK*)(FMOD_SOUND* sound, FMOD_RESULT result);
using FMOD_SOUND_PCMREADCALLBACK = FMOD_RESULT(F_CALLBACK*)(FMOD_SOUND* sound, void* data, unsigned int datalen);
using FMOD_SOUND_PCMSETPOSCALLBACK = FMOD_RESULT(F_CALLBACK*)(FMOD_SOUND* sound, int subsound, unsigned int position,
                                                              FMOD_TIMEUNIT postype);

using FMOD_FILE_OPENCALLBACK = FMOD_RESULT(F_CALLBACK*)(const char* name, int unicode, unsigned int* filesize,
                                                        void** handle, void** userdata);
using FMOD_FILE_CLOSECALLBACK = FMOD_RESULT(F_CALLBACK*)(void* handle, void* userdata);
using FMOD_FILE_READCALLBACK = FMOD_RESULT(F_CALLBACK*)(void* handle, void* buffer, unsigned int sizebytes,
                                                        unsigned int* bytesread, void* userdata);
using FMOD_FILE_SEEKCALLBACK = FMOD_RESULT(F_CALLBACK*)(void* handle, unsigned int pos, void* userdata);

using FMOD_MEMORY_ALLOCCALLBACK = void*(F_CALLBACK*)(unsigned int size, FMOD_MEMORY_TYPE type);
using FMOD_MEMORY_REALLOCCALLBACK = void*(F_CALLBACK*)(void* ptr, unsigned int size, FMOD_MEMORY_TYPE type);
using FMOD_MEMORY_FREECALLBACK = void(F_CALLBACK*)(void* ptr, FMOD_MEMORY_TYPE type);

using FMOD_3D_ROLLOFFCALLBACK = float(F_CALLBACK*)(FMOD_CHANNEL* channel, float distance);

enum FMOD_DSP_FFT_WINDOW
{
	FMOD_DSP_FFT_WINDOW_RECT,
	FMOD_DSP_FFT_WINDOW_TRIANGLE,
	FMOD_DSP_FFT_WINDOW_HAMMING,
	FMOD_DSP_FFT_WINDOW_HANNING,
	FMOD_DSP_FFT_WINDOW_BLACKMAN,
	FMOD_DSP_FFT_WINDOW_BLACKMANHARRIS,

	FMOD_DSP_FFT_WINDOW_MAX,
	FMOD_DSP_FFT_WINDOW_FORCEINT = 65536,
};

enum FMOD_DSP_RESAMPLER
{
	FMOD_DSP_RESAMPLER_NOINTERP,
	FMOD_DSP_RESAMPLER_LINEAR,
	FMOD_DSP_RESAMPLER_CUBIC,
	FMOD_DSP_RESAMPLER_SPLINE,

	FMOD_DSP_RESAMPLER_MAX,
	FMOD_DSP_RESAMPLER_FORCEINT = 65536,
};

enum FMOD_TAGTYPE
{
	FMOD_TAGTYPE_UNKNOWN = 0,
	FMOD_TAGTYPE_ID3V1,
	FMOD_TAGTYPE_ID3V2,
	FMOD_TAGTYPE_VORBISCOMMENT,
	FMOD_TAGTYPE_SHOUTCAST,
	FMOD_TAGTYPE_ICECAST,
	FMOD_TAGTYPE_ASF,
	FMOD_TAGTYPE_MIDI,
	FMOD_TAGTYPE_PLAYLIST,
	FMOD_TAGTYPE_FMOD,
	FMOD_TAGTYPE_USER,

	FMOD_TAGTYPE_MAX,
	FMOD_TAGTYPE_FORCEINT = 65536,
};

enum FMOD_TAGDATATYPE
{
	FMOD_TAGDATATYPE_BINARY = 0,
	FMOD_TAGDATATYPE_INT,
	FMOD_TAGDATATYPE_FLOAT,
	FMOD_TAGDATATYPE_STRING,
	FMOD_TAGDATATYPE_STRING_UTF16,
	FMOD_TAGDATATYPE_STRING_UTF16BE,
	FMOD_TAGDATATYPE_STRING_UTF8,
	FMOD_TAGDATATYPE_CDTOC,

	FMOD_TAGDATATYPE_MAX,
	FMOD_TAGDATATYPE_FORCEINT = 65536,
};

enum FMOD_DELAYTYPE
{
	FMOD_DELAYTYPE_END_MS,
	FMOD_DELAYTYPE_DSPCLOCK_START,
	FMOD_DELAYTYPE_DSPCLOCK_END,

	FMOD_DELAYTYPE_MAX,
	FMOD_DELAYTYPE_FORCEINT = 65536,
};

struct FMOD_TAG
{
	FMOD_TAGTYPE type;
	FMOD_TAGDATATYPE datatype;
	char* name;
	void* data;
	unsigned int datalen;
	FMOD_BOOL updated;
};

struct FMOD_CDTOC
{
	int numtracks;
	int min[100];
	int sec[100];
	int frame[100];
};

#define FMOD_TIMEUNIT_MS 0x00000001
#define FMOD_TIMEUNIT_PCM 0x00000002
#define FMOD_TIMEUNIT_PCMBYTES 0x00000004
#define FMOD_TIMEUNIT_RAWBYTES 0x00000008
#define FMOD_TIMEUNIT_MODORDER 0x00000100
#define FMOD_TIMEUNIT_MODROW 0x00000200
#define FMOD_TIMEUNIT_MODPATTERN 0x00000400
#define FMOD_TIMEUNIT_SENTENCE_MS 0x00010000
#define FMOD_TIMEUNIT_SENTENCE_PCM 0x00020000
#define FMOD_TIMEUNIT_SENTENCE_PCMBYTES 0x00040000
#define FMOD_TIMEUNIT_SENTENCE 0x00080000
#define FMOD_TIMEUNIT_SENTENCE_SUBSOUND 0x00100000
#define FMOD_TIMEUNIT_BUFFERED 0x10000000

enum FMOD_SPEAKERMAPTYPE
{
	FMOD_SPEAKERMAPTYPE_DEFAULT,
	FMOD_SPEAKERMAPTYPE_ALLMONO,
	FMOD_SPEAKERMAPTYPE_ALLSTEREO,
};

struct FMOD_CREATESOUNDEXINFO
{
private:
	int cbsize = sizeof(FMOD_CREATESOUNDEXINFO);

public:
	unsigned int length{};
	unsigned int fileoffset{};
	int numchannels{};
	int defaultfrequency{};
	FMOD_SOUND_FORMAT format{};
	unsigned int decodebuffersize{};
	int initialsubsound{};
	int numsubsounds{};
	int* inclusionlist{};
	int inclusionlistnum{};
	FMOD_SOUND_PCMREADCALLBACK pcmreadcallback{};
	FMOD_SOUND_PCMSETPOSCALLBACK pcmsetposcallback{};
	FMOD_SOUND_NONBLOCKCALLBACK nonblockcallback{};
	const char* dlsname{};
	const char* encryptionkey{};
	int maxpolyphony{};
	void* userdata{};
	FMOD_SOUND_TYPE suggestedsoundtype{};
	FMOD_FILE_OPENCALLBACK useropen{};
	FMOD_FILE_CLOSECALLBACK userclose{};
	FMOD_FILE_READCALLBACK userread{};
	FMOD_FILE_SEEKCALLBACK userseek{};
	FMOD_SPEAKERMAPTYPE speakermap{};
	FMOD_SOUNDGROUP* initialsoundgroup{};

private:
	// CryMP: missing in old FMOD
	unsigned int initialseekposition{};
	FMOD_TIMEUNIT initialseekpostype{};

public:
	FMOD_CREATESOUNDEXINFO()
	{
		if (g_hasC1Fmod)
		{
#ifdef BUILD_64BIT
			static_assert(sizeof(FMOD_CREATESOUNDEXINFO) == (0xA8 + 8));
			this->cbsize = 0xA8;
#else
			static_assert(sizeof(FMOD_CREATESOUNDEXINFO) == (0x64 + 8));
			this->cbsize = 0x64;
#endif
		}
	}
};

struct FMOD_REVERB_PROPERTIES
{
	int Instance;
	int Environment;
	float EnvSize;
	float EnvDiffusion;
	int Room;
	int RoomHF;
	int RoomLF;
	float DecayTime;
	float DecayHFRatio;
	float DecayLFRatio;
	int Reflections;
	float ReflectionsDelay;
	float ReflectionsPan[3];
	int Reverb;
	float ReverbDelay;
	float ReverbPan[3];
	float EchoTime;
	float EchoDepth;
	float ModulationTime;
	float ModulationDepth;
	float AirAbsorptionHF;
	float HFReference;
	float LFReference;
	float RoomRolloffFactor;
	float Diffusion;
	float Density;
	unsigned int Flags;
};

#define FMOD_REVERB_FLAGS_DECAYTIMESCALE 0x00000001
#define FMOD_REVERB_FLAGS_REFLECTIONSSCALE 0x00000002
#define FMOD_REVERB_FLAGS_REFLECTIONSDELAYSCALE 0x00000004
#define FMOD_REVERB_FLAGS_REVERBSCALE 0x00000008
#define FMOD_REVERB_FLAGS_REVERBDELAYSCALE 0x00000010
#define FMOD_REVERB_FLAGS_DECAYHFLIMIT 0x00000020
#define FMOD_REVERB_FLAGS_ECHOTIMESCALE 0x00000040
#define FMOD_REVERB_FLAGS_MODULATIONTIMESCALE 0x00000080
#define FMOD_REVERB_FLAGS_CORE0 0x00000100
#define FMOD_REVERB_FLAGS_CORE1 0x00000200
#define FMOD_REVERB_FLAGS_HIGHQUALITYREVERB 0x00000400
#define FMOD_REVERB_FLAGS_HIGHQUALITYDPL2REVERB 0x00000800

#define FMOD_REVERB_FLAGS_DEFAULT                                                                                      \
	(FMOD_REVERB_FLAGS_DECAYTIMESCALE | FMOD_REVERB_FLAGS_REFLECTIONSSCALE |                                       \
	 FMOD_REVERB_FLAGS_REFLECTIONSDELAYSCALE | FMOD_REVERB_FLAGS_REVERBSCALE |                                     \
	 FMOD_REVERB_FLAGS_REVERBDELAYSCALE | FMOD_REVERB_FLAGS_DECAYHFLIMIT | FMOD_REVERB_FLAGS_CORE0 |               \
	 FMOD_REVERB_FLAGS_CORE1)

struct FMOD_REVERB_CHANNELPROPERTIES
{
	int Direct;
	int DirectHF;
	int Room;
	int RoomHF;
	int Obstruction;
	float ObstructionLFRatio;
	int Occlusion;
	float OcclusionLFRatio;
	float OcclusionRoomRatio;
	float OcclusionDirectRatio;
	int Exclusion;
	float ExclusionLFRatio;
	int OutsideVolumeHF;
	float DopplerFactor;
	float RolloffFactor;
	float RoomRolloffFactor;
	float AirAbsorptionFactor;
	unsigned int Flags;
};

#define FMOD_REVERB_CHANNELFLAGS_DIRECTHFAUTO 0x00000001
#define FMOD_REVERB_CHANNELFLAGS_ROOMAUTO 0x00000002
#define FMOD_REVERB_CHANNELFLAGS_ROOMHFAUTO 0x00000004
#define FMOD_REVERB_CHANNELFLAGS_INSTANCE0 0x00000008
#define FMOD_REVERB_CHANNELFLAGS_INSTANCE1 0x00000010
#define FMOD_REVERB_CHANNELFLAGS_INSTANCE2 0x00000020
#define FMOD_REVERB_CHANNELFLAGS_INSTANCE3 0x00000040

#define FMOD_REVERB_CHANNELFLAGS_DEFAULT                                                                               \
	(FMOD_REVERB_CHANNELFLAGS_DIRECTHFAUTO | FMOD_REVERB_CHANNELFLAGS_ROOMAUTO |                                   \
	 FMOD_REVERB_CHANNELFLAGS_ROOMHFAUTO | FMOD_REVERB_CHANNELFLAGS_INSTANCE0)

struct FMOD_ADVANCEDSETTINGS
{
private:
	int cbsize = sizeof(FMOD_ADVANCEDSETTINGS);

public:
	int maxMPEGcodecs{};
	int maxADPCMcodecs{};
	int maxXMAcodecs{};
	int maxPCMcodecs{};
	int ASIONumChannels{};
	char** ASIOChannelList{};
	FMOD_SPEAKER* ASIOSpeakerList{};
	int max3DReverbDSPs{};
	float HRTFMinAngle{};
	float HRTFMaxAngle{};
	float HRTFFreq{};
	float vol0virtualvol{};
	int eventqueuesize{};

private:
	// CryMP: missing in old FMOD
	unsigned int defaultDecodeBufferSize{};
	char* debugLogFilename{};
	unsigned short profileport{};

public:
	FMOD_ADVANCEDSETTINGS()
	{
		if (g_hasC1Fmod)
		{
#ifdef BUILD_64BIT
			static_assert(sizeof(FMOD_ADVANCEDSETTINGS) == (0x40 + 24));
			this->cbsize = 0x40;
#else
			static_assert(sizeof(FMOD_ADVANCEDSETTINGS) == (0x38 + 12));
			this->cbsize = 0x38;
#endif
		}
	}
};

enum FMOD_CHANNELINDEX
{
	FMOD_CHANNEL_FREE = -1,
	FMOD_CHANNEL_REUSE = -2,
};

struct FMOD_CODEC_STATE;
struct FMOD_CODEC_WAVEFORMAT;

using FMOD_CODEC_OPENCALLBACK = FMOD_RESULT(F_CALLBACK*)(FMOD_CODEC_STATE* codec_state, FMOD_MODE usermode,
                                                         FMOD_CREATESOUNDEXINFO* userexinfo);
using FMOD_CODEC_CLOSECALLBACK = FMOD_RESULT(F_CALLBACK*)(FMOD_CODEC_STATE* codec_state);
using FMOD_CODEC_READCALLBACK = FMOD_RESULT(F_CALLBACK*)(FMOD_CODEC_STATE* codec_state, void* buffer,
                                                         unsigned int sizebytes, unsigned int* bytesread);
using FMOD_CODEC_GETLENGTHCALLBACK = FMOD_RESULT(F_CALLBACK*)(FMOD_CODEC_STATE* codec_state, unsigned int* length,
                                                              FMOD_TIMEUNIT lengthtype);
using FMOD_CODEC_SETPOSITIONCALLBACK = FMOD_RESULT(F_CALLBACK*)(FMOD_CODEC_STATE* codec_state, int subsound,
                                                                unsigned int position, FMOD_TIMEUNIT postype);
using FMOD_CODEC_GETPOSITIONCALLBACK = FMOD_RESULT(F_CALLBACK*)(FMOD_CODEC_STATE* codec_state, unsigned int* position,
                                                                FMOD_TIMEUNIT postype);
using FMOD_CODEC_SOUNDCREATECALLBACK = FMOD_RESULT(F_CALLBACK*)(FMOD_CODEC_STATE* codec_state, int subsound,
                                                                FMOD_SOUND* sound);
using FMOD_CODEC_METADATACALLBACK = FMOD_RESULT(F_CALLBACK*)(FMOD_CODEC_STATE* codec_state, FMOD_TAGTYPE tagtype,
                                                             char* name, void* data, unsigned int datalen,
                                                             FMOD_TAGDATATYPE datatype, int unique);
using FMOD_CODEC_GETWAVEFORMAT = FMOD_RESULT(F_CALLBACK*)(FMOD_CODEC_STATE* codec_state, int index,
                                                          FMOD_CODEC_WAVEFORMAT* waveformat);

struct FMOD_CODEC_DESCRIPTION
{
	const char* name;
	unsigned int version;
	int defaultasstream;
	FMOD_TIMEUNIT timeunits;
	FMOD_CODEC_OPENCALLBACK open;
	FMOD_CODEC_CLOSECALLBACK close;
	FMOD_CODEC_READCALLBACK read;
	FMOD_CODEC_GETLENGTHCALLBACK getlength;
	FMOD_CODEC_SETPOSITIONCALLBACK setposition;
	FMOD_CODEC_GETPOSITIONCALLBACK getposition;
	FMOD_CODEC_SOUNDCREATECALLBACK soundcreate;
	FMOD_CODEC_GETWAVEFORMAT getwaveformat;
};

struct FMOD_CODEC_WAVEFORMAT
{
	char name[256];
	FMOD_SOUND_FORMAT format;
	int channels;
	int frequency;
	unsigned int lengthbytes;
	unsigned int lengthpcm;
	int blockalign;
	int loopstart;
	int loopend;
	FMOD_MODE mode;
	unsigned int channelmask;
};

struct FMOD_CODEC_STATE
{
	int numsubsounds;
	FMOD_CODEC_WAVEFORMAT* waveformat;
	void* plugindata;

	void* filehandle;
	unsigned int filesize;
	FMOD_FILE_READCALLBACK fileread;
	FMOD_FILE_SEEKCALLBACK fileseek;
	FMOD_CODEC_METADATACALLBACK metadata;
};

struct FMOD_DSP_STATE;

using FMOD_DSP_CREATECALLBACK = FMOD_RESULT(F_CALLBACK*)(FMOD_DSP_STATE* dsp_state);
using FMOD_DSP_RELEASECALLBACK = FMOD_RESULT(F_CALLBACK*)(FMOD_DSP_STATE* dsp_state);
using FMOD_DSP_RESETCALLBACK = FMOD_RESULT(F_CALLBACK*)(FMOD_DSP_STATE* dsp_state);
using FMOD_DSP_READCALLBACK = FMOD_RESULT(F_CALLBACK*)(FMOD_DSP_STATE* dsp_state, float* inbuffer, float* outbuffer,
                                                       unsigned int length, int inchannels, int outchannels);
using FMOD_DSP_SETPOSITIONCALLBACK = FMOD_RESULT(F_CALLBACK*)(FMOD_DSP_STATE* dsp_state, unsigned int pos);
using FMOD_DSP_SETPARAMCALLBACK = FMOD_RESULT(F_CALLBACK*)(FMOD_DSP_STATE* dsp_state, int index, float value);
using FMOD_DSP_GETPARAMCALLBACK = FMOD_RESULT(F_CALLBACK*)(FMOD_DSP_STATE* dsp_state, int index, float* value,
                                                           char* valuestr);
using FMOD_DSP_DIALOGCALLBACK = FMOD_RESULT(F_CALLBACK*)(FMOD_DSP_STATE* dsp_state, void* hwnd, int show);

enum FMOD_DSP_TYPE
{
	FMOD_DSP_TYPE_UNKNOWN,
	FMOD_DSP_TYPE_MIXER,
	FMOD_DSP_TYPE_OSCILLATOR,
	FMOD_DSP_TYPE_LOWPASS,
	FMOD_DSP_TYPE_ITLOWPASS,
	FMOD_DSP_TYPE_HIGHPASS,
	FMOD_DSP_TYPE_ECHO,
	FMOD_DSP_TYPE_FLANGE,
	FMOD_DSP_TYPE_DISTORTION,
	FMOD_DSP_TYPE_NORMALIZE,
	FMOD_DSP_TYPE_PARAMEQ,
	FMOD_DSP_TYPE_PITCHSHIFT,
	FMOD_DSP_TYPE_CHORUS,
	FMOD_DSP_TYPE_REVERB,
	FMOD_DSP_TYPE_VSTPLUGIN,
	FMOD_DSP_TYPE_WINAMPPLUGIN,
	FMOD_DSP_TYPE_ITECHO,
	FMOD_DSP_TYPE_COMPRESSOR,
	FMOD_DSP_TYPE_SFXREVERB,
	FMOD_DSP_TYPE_LOWPASS_SIMPLE,
	FMOD_DSP_TYPE_FORCEINT = 65536,
};

struct FMOD_DSP_PARAMETERDESC
{
	float min;
	float max;
	float defaultval;
	char name[16];
	char label[16];
	const char* description;
};

struct FMOD_DSP_DESCRIPTION
{
	char name[32];
	unsigned int version;
	int channels;
	FMOD_DSP_CREATECALLBACK create;
	FMOD_DSP_RELEASECALLBACK release;
	FMOD_DSP_RESETCALLBACK reset;
	FMOD_DSP_READCALLBACK read;
	FMOD_DSP_SETPOSITIONCALLBACK setposition;

	int numparameters;
	FMOD_DSP_PARAMETERDESC* paramdesc;
	FMOD_DSP_SETPARAMCALLBACK setparameter;
	FMOD_DSP_GETPARAMCALLBACK getparameter;
	FMOD_DSP_DIALOGCALLBACK config;
	int configwidth;
	int configheight;
	void* userdata;
};

struct FMOD_DSP_STATE
{
	FMOD_DSP* instance;
	void* plugindata;
};

enum FMOD_DSP_OSCILLATOR
{
	FMOD_DSP_OSCILLATOR_TYPE,
	FMOD_DSP_OSCILLATOR_RATE,
};

enum FMOD_DSP_LOWPASS
{
	FMOD_DSP_LOWPASS_CUTOFF,
	FMOD_DSP_LOWPASS_RESONANCE,
};

enum FMOD_DSP_ITLOWPASS
{
	FMOD_DSP_ITLOWPASS_CUTOFF,
	FMOD_DSP_ITLOWPASS_RESONANCE,
};

enum FMOD_DSP_HIGHPASS
{
	FMOD_DSP_HIGHPASS_CUTOFF,
	FMOD_DSP_HIGHPASS_RESONANCE,
};

enum FMOD_DSP_ECHO
{
	FMOD_DSP_ECHO_DELAY,
	FMOD_DSP_ECHO_DECAYRATIO,
	FMOD_DSP_ECHO_MAXCHANNELS,
	FMOD_DSP_ECHO_DRYMIX,
	FMOD_DSP_ECHO_WETMIX,
};

enum FMOD_DSP_FLANGE
{
	FMOD_DSP_FLANGE_DRYMIX,
	FMOD_DSP_FLANGE_WETMIX,
	FMOD_DSP_FLANGE_DEPTH,
	FMOD_DSP_FLANGE_RATE,
};

enum FMOD_DSP_DISTORTION
{
	FMOD_DSP_DISTORTION_LEVEL,
};

enum FMOD_DSP_NORMALIZE
{
	FMOD_DSP_NORMALIZE_FADETIME,
	FMOD_DSP_NORMALIZE_THRESHHOLD,
	FMOD_DSP_NORMALIZE_MAXAMP,
};

enum FMOD_DSP_PARAMEQ
{
	FMOD_DSP_PARAMEQ_CENTER,
	FMOD_DSP_PARAMEQ_BANDWIDTH,
	FMOD_DSP_PARAMEQ_GAIN,
};

enum FMOD_DSP_PITCHSHIFT
{
	FMOD_DSP_PITCHSHIFT_PITCH,
	FMOD_DSP_PITCHSHIFT_FFTSIZE,
	FMOD_DSP_PITCHSHIFT_OVERLAP,
	FMOD_DSP_PITCHSHIFT_MAXCHANNELS,
};

enum FMOD_DSP_CHORUS
{
	FMOD_DSP_CHORUS_DRYMIX,
	FMOD_DSP_CHORUS_WETMIX1,
	FMOD_DSP_CHORUS_WETMIX2,
	FMOD_DSP_CHORUS_WETMIX3,
	FMOD_DSP_CHORUS_DELAY,
	FMOD_DSP_CHORUS_RATE,
	FMOD_DSP_CHORUS_DEPTH,
	FMOD_DSP_CHORUS_FEEDBACK,
};

enum FMOD_DSP_REVERB
{
	FMOD_DSP_REVERB_ROOMSIZE,
	FMOD_DSP_REVERB_DAMP,
	FMOD_DSP_REVERB_WETMIX,
	FMOD_DSP_REVERB_DRYMIX,
	FMOD_DSP_REVERB_WIDTH,
	FMOD_DSP_REVERB_MODE,
};

enum FMOD_DSP_ITECHO
{
	FMOD_DSP_ITECHO_WETDRYMIX,
	FMOD_DSP_ITECHO_FEEDBACK,
	FMOD_DSP_ITECHO_LEFTDELAY,
	FMOD_DSP_ITECHO_RIGHTDELAY,
	FMOD_DSP_ITECHO_PANDELAY,
};

enum FMOD_DSP_COMPRESSOR
{
	FMOD_DSP_COMPRESSOR_THRESHOLD,
	FMOD_DSP_COMPRESSOR_ATTACK,
	FMOD_DSP_COMPRESSOR_RELEASE,
	FMOD_DSP_COMPRESSOR_GAINMAKEUP,
};

enum FMOD_DSP_SFXREVERB
{
	FMOD_DSP_SFXREVERB_DRYLEVEL,
	FMOD_DSP_SFXREVERB_ROOM,
	FMOD_DSP_SFXREVERB_ROOMHF,
	FMOD_DSP_SFXREVERB_ROOMROLLOFFFACTOR,
	FMOD_DSP_SFXREVERB_DECAYTIME,
	FMOD_DSP_SFXREVERB_DECAYHFRATIO,
	FMOD_DSP_SFXREVERB_REFLECTIONSLEVEL,
	FMOD_DSP_SFXREVERB_REFLECTIONSDELAY,
	FMOD_DSP_SFXREVERB_REVERBLEVEL,
	FMOD_DSP_SFXREVERB_REVERBDELAY,
	FMOD_DSP_SFXREVERB_DIFFUSION,
	FMOD_DSP_SFXREVERB_DENSITY,
	FMOD_DSP_SFXREVERB_HFREFERENCE,
	FMOD_DSP_SFXREVERB_ROOMLF,
	FMOD_DSP_SFXREVERB_LFREFERENCE,
};

enum FMOD_DSP_LOWPASS_SIMPLE
{
	FMOD_DSP_LOWPASS_SIMPLE_CUTOFF,
};

const char* FMOD_ErrorString(FMOD_RESULT errcode);

struct FMOD_EVENT;

using FMOD_EVENT_INITFLAGS = unsigned int;
using FMOD_EVENT_MODE = unsigned int;
using FMOD_EVENT_STATE = unsigned int;

#define FMOD_EVENT_INIT_NORMAL 0x00000000
#define FMOD_EVENT_INIT_USER_ASSETMANAGER 0x00000001
#define FMOD_EVENT_INIT_FAIL_ON_MAXSTREAMS 0x00000002
#define FMOD_EVENT_INIT_DONTUSENAMES 0x00000004
#define FMOD_EVENT_INIT_UPPERCASE_FILENAMES 0x00000008
#define FMOD_EVENT_INIT_SEARCH_PLUGINS 0x00000010

#define FMOD_EVENT_DEFAULT 0x00000000
#define FMOD_EVENT_NONBLOCKING 0x00000001
#define FMOD_EVENT_ERROR_ON_DISKACCESS 0x00000002
#define FMOD_EVENT_INFOONLY 0x00000004

#define FMOD_EVENT_STATE_READY 0x00000001
#define FMOD_EVENT_STATE_LOADING 0x00000002
#define FMOD_EVENT_STATE_ERROR 0x00000004
#define FMOD_EVENT_STATE_PLAYING 0x00000008
#define FMOD_EVENT_STATE_CHANNELSACTIVE 0x00000010
#define FMOD_EVENT_STATE_INFOONLY 0x00000020
#define FMOD_EVENT_STATE_STARVING 0x00000040

enum FMOD_EVENT_PROPERTY
{
	FMOD_EVENTPROPERTY_NAME = 0,
	FMOD_EVENTPROPERTY_VOLUME,
	FMOD_EVENTPROPERTY_VOLUMERANDOMIZATION,
	FMOD_EVENTPROPERTY_PITCH,
	FMOD_EVENTPROPERTY_PITCH_OCTAVES,
	FMOD_EVENTPROPERTY_PITCH_SEMITONES,
	FMOD_EVENTPROPERTY_PITCH_TONES,
	FMOD_EVENTPROPERTY_PITCHRANDOMIZATION,
	FMOD_EVENTPROPERTY_PITCHRANDOMIZATION_OCTAVES,
	FMOD_EVENTPROPERTY_PITCHRANDOMIZATION_SEMITONES,
	FMOD_EVENTPROPERTY_PITCHRANDOMIZATION_TONES,
	FMOD_EVENTPROPERTY_PRIORITY,
	FMOD_EVENTPROPERTY_MAX_PLAYBACKS,
	FMOD_EVENTPROPERTY_MAX_PLAYBACKS_BEHAVIOR,
	FMOD_EVENTPROPERTY_MODE,
	FMOD_EVENTPROPERTY_3D_ROLLOFF,
	FMOD_EVENTPROPERTY_3D_MINDISTANCE,
	FMOD_EVENTPROPERTY_3D_MAXDISTANCE,
	FMOD_EVENTPROPERTY_3D_POSITION,
	FMOD_EVENTPROPERTY_3D_CONEINSIDEANGLE,
	FMOD_EVENTPROPERTY_3D_CONEOUTSIDEANGLE,
	FMOD_EVENTPROPERTY_3D_CONEOUTSIDEVOLUME,
	FMOD_EVENTPROPERTY_3D_DOPPLERSCALE,
	FMOD_EVENTPROPERTY_3D_SPEAKERSPREAD,
	FMOD_EVENTPROPERTY_3D_PANLEVEL,
	FMOD_EVENTPROPERTY_SPEAKER_L,
	FMOD_EVENTPROPERTY_SPEAKER_C,
	FMOD_EVENTPROPERTY_SPEAKER_R,
	FMOD_EVENTPROPERTY_SPEAKER_LS,
	FMOD_EVENTPROPERTY_SPEAKER_RS,
	FMOD_EVENTPROPERTY_SPEAKER_LR,
	FMOD_EVENTPROPERTY_SPEAKER_RR,
	FMOD_EVENTPROPERTY_SPEAKER_LFE,
	FMOD_EVENTPROPERTY_REVERBWETLEVEL,
	FMOD_EVENTPROPERTY_ONESHOT,
	FMOD_EVENTPROPERTY_FADEIN,
	FMOD_EVENTPROPERTY_FADEOUT,
	FMOD_EVENTPROPERTY_REVERBDRYLEVEL,
	FMOD_EVENTPROPERTY_TIMEOFFSET,
	FMOD_EVENTPROPERTY_SPAWNINTENSITY,
	FMOD_EVENTPROPERTY_SPAWNINTENSITY_RANDOMIZATION,
	FMOD_EVENTPROPERTY_WII_CONTROLLERSPEAKER,
	FMOD_EVENTPROPERTY_3D_POSRANDOMIZATION,
	FMOD_EVENTPROPERTY_USER_BASE,
};

// CryMP: some event properties are missing in old FMOD
inline int AdjustEventPropertyForOldFmod(int property)
{
	switch (property)
	{
		// missing
		case FMOD_EVENTPROPERTY_PITCH_OCTAVES:
		case FMOD_EVENTPROPERTY_PITCH_SEMITONES:
		case FMOD_EVENTPROPERTY_PITCH_TONES:
		case FMOD_EVENTPROPERTY_PITCHRANDOMIZATION_OCTAVES:
		case FMOD_EVENTPROPERTY_PITCHRANDOMIZATION_SEMITONES:
		case FMOD_EVENTPROPERTY_PITCHRANDOMIZATION_TONES:
		{
			return -1;
		}
	}

	if (property > FMOD_EVENTPROPERTY_PITCHRANDOMIZATION)
	{
		return property - 6;
	}
	else if (property > FMOD_EVENTPROPERTY_PITCH)
	{
		return property - 3;
	}

	return property;
}

// CryMP: missing in old FMOD
enum FMOD_EVENT_PITCHUNITS
{
	FMOD_EVENT_PITCHUNITS_RAW = 0,
	FMOD_EVENT_PITCHUNITS_OCTAVES,
	FMOD_EVENT_PITCHUNITS_SEMITONES,
	FMOD_EVENT_PITCHUNITS_TONES,
};

enum FMOD_EVENT_RESOURCE
{
	FMOD_EVENT_RESOURCE_STREAMS_AND_SAMPLES,
	FMOD_EVENT_RESOURCE_STREAMS,
	FMOD_EVENT_RESOURCE_SAMPLES,
};

enum FMOD_EVENT_CALLBACKTYPE
{
	FMOD_EVENT_CALLBACKTYPE_SYNCPOINT,
	FMOD_EVENT_CALLBACKTYPE_SOUNDDEF_START,
	FMOD_EVENT_CALLBACKTYPE_SOUNDDEF_END,
	FMOD_EVENT_CALLBACKTYPE_STOLEN,
	FMOD_EVENT_CALLBACKTYPE_EVENTFINISHED,
	FMOD_EVENT_CALLBACKTYPE_NET_MODIFIED,
	FMOD_EVENT_CALLBACKTYPE_SOUNDDEF_CREATE,
	FMOD_EVENT_CALLBACKTYPE_SOUNDDEF_RELEASE,
	FMOD_EVENT_CALLBACKTYPE_SOUNDDEF_INFO,
	FMOD_EVENT_CALLBACKTYPE_EVENTSTARTED,
	FMOD_EVENT_CALLBACKTYPE_SOUNDDEF_SELECTINDEX,
};

struct FMOD_EVENT_WAVEBANKINFO
{
	char* name;
	int streamrefcnt;
	int samplerefcnt;
	int numstreams;
	int maxstreams;
	int streamsinuse;
	unsigned int streammemory;
	unsigned int samplememory;
};

struct FMOD_EVENT_SYSTEMINFO
{
	int numevents;
	int eventmemory;
	int numinstances;
	int instancememory;
	int dspmemory;
	int numwavebanks;
	FMOD_EVENT_WAVEBANKINFO* wavebankinfo;
	int numplayingevents;
	FMOD_EVENT** playingevents;
};

struct FMOD_EVENT_INFO
{
	int memoryused;
	int positionms;
	int lengthms;
	int channelsplaying;
	int instancesactive;
	char** wavebanknames;
	unsigned int projectid;
	unsigned int systemid;
	float audibility;
	int numinstances;
	FMOD_EVENT** instances;
};

struct FMOD_EVENT_LOADINFO
{
	unsigned int size;
	char* encryptionkey;
	float sounddefentrylimit;
	unsigned int loadfrommemory_length;
};

using FMOD_EVENT_CALLBACK = FMOD_RESULT(F_CALLBACK*)(FMOD_EVENT* event, FMOD_EVENT_CALLBACKTYPE type, void* param1,
                                                     void* param2, void* userdata);

#define FMOD_EVENT_NET_PORT 17997

namespace FMOD {

class EventSystem;

FMOD_RESULT F_API NetEventSystem_Init(EventSystem* eventsystem, unsigned short port = FMOD_EVENT_NET_PORT);
FMOD_RESULT F_API NetEventSystem_Update();
FMOD_RESULT F_API NetEventSystem_Shutdown();
FMOD_RESULT F_API NetEventSystem_GetVersion(unsigned int* version);

class System;
class Sound;
class Channel;
class ChannelGroup;
class SoundGroup;
class Reverb;
class DSP;
class DSPConnection;
class Geometry;

FMOD_RESULT Memory_Initialize(void* poolmem, int poollen, FMOD_MEMORY_ALLOCCALLBACK useralloc,
                              FMOD_MEMORY_REALLOCCALLBACK userrealloc, FMOD_MEMORY_FREECALLBACK userfree);
FMOD_RESULT Memory_GetStats(int* currentalloced, int* maxalloced);
FMOD_RESULT Debug_SetLevel(FMOD_DEBUGLEVEL level);
FMOD_RESULT Debug_GetLevel(FMOD_DEBUGLEVEL* level);
FMOD_RESULT File_SetDiskBusy(int busy);
FMOD_RESULT File_GetDiskBusy(int* busy);
FMOD_RESULT System_Create(System** system);

class System
{
private:
	System();

public:
	FMOD_RESULT F_API release();

	FMOD_RESULT F_API setOutput(FMOD_OUTPUTTYPE output);
	FMOD_RESULT F_API getOutput(FMOD_OUTPUTTYPE* output);
	FMOD_RESULT F_API getNumDrivers(int* numdrivers);
	FMOD_RESULT F_API getDriverInfo(int id, char* name, int namelen, FMOD_GUID* guid);
	FMOD_RESULT F_API getDriverCaps(int id, FMOD_CAPS* caps, int* minfrequency, int* maxfrequency,
	                                FMOD_SPEAKERMODE* controlpanelspeakermode);
	FMOD_RESULT F_API setDriver(int driver);
	FMOD_RESULT F_API getDriver(int* driver);
	FMOD_RESULT F_API setHardwareChannels(int min2d, int max2d, int min3d, int max3d);
	FMOD_RESULT F_API setSoftwareChannels(int numsoftwarechannels);
	FMOD_RESULT F_API getSoftwareChannels(int* numsoftwarechannels);
	FMOD_RESULT F_API setSoftwareFormat(int samplerate, FMOD_SOUND_FORMAT format, int numoutputchannels,
	                                    int maxinputchannels, FMOD_DSP_RESAMPLER resamplemethod);
	FMOD_RESULT F_API getSoftwareFormat(int* samplerate, FMOD_SOUND_FORMAT* format, int* numoutputchannels,
	                                    int* maxinputchannels, FMOD_DSP_RESAMPLER* resamplemethod, int* bits);
	FMOD_RESULT F_API setDSPBufferSize(unsigned int bufferlength, int numbuffers);
	FMOD_RESULT F_API getDSPBufferSize(unsigned int* bufferlength, int* numbuffers);
	FMOD_RESULT F_API setFileSystem(FMOD_FILE_OPENCALLBACK useropen, FMOD_FILE_CLOSECALLBACK userclose,
	                                FMOD_FILE_READCALLBACK userread, FMOD_FILE_SEEKCALLBACK userseek,
	                                int blockalign);
	FMOD_RESULT F_API attachFileSystem(FMOD_FILE_OPENCALLBACK useropen, FMOD_FILE_CLOSECALLBACK userclose,
	                                   FMOD_FILE_READCALLBACK userread, FMOD_FILE_SEEKCALLBACK userseek);
	FMOD_RESULT F_API setAdvancedSettings(FMOD_ADVANCEDSETTINGS* settings);
	FMOD_RESULT F_API getAdvancedSettings(FMOD_ADVANCEDSETTINGS* settings);
	FMOD_RESULT F_API setSpeakerMode(FMOD_SPEAKERMODE speakermode);
	FMOD_RESULT F_API getSpeakerMode(FMOD_SPEAKERMODE* speakermode);
	FMOD_RESULT F_API setCallback(FMOD_SYSTEM_CALLBACKTYPE type, FMOD_SYSTEM_CALLBACK callback);

	FMOD_RESULT F_API setPluginPath(const char* path);
	FMOD_RESULT F_API loadPlugin(const char* filename, FMOD_PLUGINTYPE* plugintype, int* index);
	FMOD_RESULT F_API getNumPlugins(FMOD_PLUGINTYPE plugintype, int* numplugins);
	FMOD_RESULT F_API getPluginInfo(FMOD_PLUGINTYPE plugintype, int index, char* name, int namelen,
	                                unsigned int* version);
	FMOD_RESULT F_API unloadPlugin(FMOD_PLUGINTYPE plugintype, int index);
	FMOD_RESULT F_API setOutputByPlugin(int index);
	FMOD_RESULT F_API getOutputByPlugin(int* index);
	FMOD_RESULT F_API createCodec(FMOD_CODEC_DESCRIPTION* description);

	FMOD_RESULT F_API init(int maxchannels, FMOD_INITFLAGS flags, void* extradriverdata);
	FMOD_RESULT F_API close();

	FMOD_RESULT F_API update();

	FMOD_RESULT F_API set3DSettings(float dopplerscale, float distancefactor, float rolloffscale);
	FMOD_RESULT F_API get3DSettings(float* dopplerscale, float* distancefactor, float* rolloffscale);
	FMOD_RESULT F_API set3DNumListeners(int numlisteners);
	FMOD_RESULT F_API get3DNumListeners(int* numlisteners);
	FMOD_RESULT F_API set3DListenerAttributes(int listener, const FMOD_VECTOR* pos, const FMOD_VECTOR* vel,
	                                          const FMOD_VECTOR* forward, const FMOD_VECTOR* up);
	FMOD_RESULT F_API get3DListenerAttributes(int listener, FMOD_VECTOR* pos, FMOD_VECTOR* vel,
	                                          FMOD_VECTOR* forward, FMOD_VECTOR* up);
	FMOD_RESULT F_API set3DRolloffCallback(FMOD_3D_ROLLOFFCALLBACK callback);
	FMOD_RESULT F_API set3DSpeakerPosition(FMOD_SPEAKER speaker, float x, float y, bool active);
	FMOD_RESULT F_API get3DSpeakerPosition(FMOD_SPEAKER speaker, float* x, float* y, bool* active);

	FMOD_RESULT F_API setStreamBufferSize(unsigned int filebuffersize, FMOD_TIMEUNIT filebuffersizetype);
	FMOD_RESULT F_API getStreamBufferSize(unsigned int* filebuffersize, FMOD_TIMEUNIT* filebuffersizetype);

	FMOD_RESULT F_API getVersion(unsigned int* version);
	FMOD_RESULT F_API getOutputHandle(void** handle);
	FMOD_RESULT F_API getChannelsPlaying(int* channels);
	FMOD_RESULT F_API getHardwareChannels(int* num2d, int* num3d, int* total);
	FMOD_RESULT F_API getCPUUsage(float* dsp, float* stream, float* update, float* total);
	FMOD_RESULT F_API getSoundRAM(int* currentalloced, int* maxalloced, int* total);
	FMOD_RESULT F_API getNumCDROMDrives(int* numdrives);
	FMOD_RESULT F_API getCDROMDriveName(int drive, char* drivename, int drivenamelen, char* scsiname,
	                                    int scsinamelen, char* devicename, int devicenamelen);
	FMOD_RESULT F_API getSpectrum(float* spectrumarray, int numvalues, int channeloffset,
	                              FMOD_DSP_FFT_WINDOW windowtype);
	FMOD_RESULT F_API getWaveData(float* wavearray, int numvalues, int channeloffset);

	FMOD_RESULT F_API createSound(const char* name_or_data, FMOD_MODE mode, FMOD_CREATESOUNDEXINFO* exinfo,
	                              Sound** sound);
	FMOD_RESULT F_API createStream(const char* name_or_data, FMOD_MODE mode, FMOD_CREATESOUNDEXINFO* exinfo,
	                               Sound** sound);
	FMOD_RESULT F_API createDSP(FMOD_DSP_DESCRIPTION* description, DSP** dsp);
	FMOD_RESULT F_API createDSPByType(FMOD_DSP_TYPE type, DSP** dsp);
	FMOD_RESULT F_API createDSPByIndex(int index, DSP** dsp);
	FMOD_RESULT F_API createChannelGroup(const char* name, ChannelGroup** channelgroup);
	FMOD_RESULT F_API createSoundGroup(const char* name, SoundGroup** soundgroup);
	FMOD_RESULT F_API createReverb(Reverb** reverb);

	FMOD_RESULT F_API playSound(FMOD_CHANNELINDEX channelid, Sound* sound, bool paused, Channel** channel);
	FMOD_RESULT F_API playDSP(FMOD_CHANNELINDEX channelid, DSP* dsp, bool paused, Channel** channel);
	FMOD_RESULT F_API getChannel(int channelid, Channel** channel);
	FMOD_RESULT F_API getMasterChannelGroup(ChannelGroup** channelgroup);
	FMOD_RESULT F_API getMasterSoundGroup(SoundGroup** soundgroup);

	FMOD_RESULT F_API setReverbProperties(const FMOD_REVERB_PROPERTIES* prop);
	FMOD_RESULT F_API getReverbProperties(FMOD_REVERB_PROPERTIES* prop);
	FMOD_RESULT F_API setReverbAmbientProperties(FMOD_REVERB_PROPERTIES* prop);
	FMOD_RESULT F_API getReverbAmbientProperties(FMOD_REVERB_PROPERTIES* prop);

	FMOD_RESULT F_API getDSPHead(DSP** dsp);
	FMOD_RESULT F_API addDSP(DSP* dsp, DSPConnection** connection);
	FMOD_RESULT F_API lockDSP();
	FMOD_RESULT F_API unlockDSP();
	FMOD_RESULT F_API getDSPClock(unsigned int* hi, unsigned int* lo);

	FMOD_RESULT F_API setRecordDriver(int driver);
	FMOD_RESULT F_API getRecordDriver(int* driver);
	FMOD_RESULT F_API getRecordNumDrivers(int* numdrivers);
	FMOD_RESULT F_API getRecordDriverInfo(int id, char* name, int namelen, FMOD_GUID* guid);
	FMOD_RESULT F_API getRecordDriverCaps(int id, FMOD_CAPS* caps, int* minfrequency, int* maxfrequency);
	FMOD_RESULT F_API getRecordPosition(unsigned int* position);

	FMOD_RESULT F_API recordStart(Sound* sound, bool loop);
	FMOD_RESULT F_API recordStop();
	FMOD_RESULT F_API isRecording(bool* recording);

	FMOD_RESULT F_API createGeometry(int maxpolygons, int maxvertices, Geometry** geometry);
	FMOD_RESULT F_API setGeometrySettings(float maxworldsize);
	FMOD_RESULT F_API getGeometrySettings(float* maxworldsize);
	FMOD_RESULT F_API loadGeometry(const void* data, int datasize, Geometry** geometry);

	FMOD_RESULT F_API setNetworkProxy(const char* proxy);
	FMOD_RESULT F_API getNetworkProxy(char* proxy, int proxylen);
	FMOD_RESULT F_API setNetworkTimeout(int timeout);
	FMOD_RESULT F_API getNetworkTimeout(int* timeout);

	FMOD_RESULT F_API setUserData(void* userdata);
	FMOD_RESULT F_API getUserData(void** userdata);
};

class Sound
{
private:
	Sound();

public:
	FMOD_RESULT F_API release();
	FMOD_RESULT F_API getSystemObject(System** system);

	FMOD_RESULT F_API lock(unsigned int offset, unsigned int length, void** ptr1, void** ptr2, unsigned int* len1,
	                       unsigned int* len2);
	FMOD_RESULT F_API unlock(void* ptr1, void* ptr2, unsigned int len1, unsigned int len2);
	FMOD_RESULT F_API setDefaults(float frequency, float volume, float pan, int priority);
	FMOD_RESULT F_API getDefaults(float* frequency, float* volume, float* pan, int* priority);
	FMOD_RESULT F_API setVariations(float frequencyvar, float volumevar, float panvar);
	FMOD_RESULT F_API getVariations(float* frequencyvar, float* volumevar, float* panvar);
	FMOD_RESULT F_API set3DMinMaxDistance(float min, float max);
	FMOD_RESULT F_API get3DMinMaxDistance(float* min, float* max);
	FMOD_RESULT F_API set3DConeSettings(float insideconeangle, float outsideconeangle, float outsidevolume);
	FMOD_RESULT F_API get3DConeSettings(float* insideconeangle, float* outsideconeangle, float* outsidevolume);
	FMOD_RESULT F_API set3DCustomRolloff(FMOD_VECTOR* points, int numpoints);
	FMOD_RESULT F_API get3DCustomRolloff(FMOD_VECTOR** points, int* numpoints);
	FMOD_RESULT F_API setSubSound(int index, Sound* subsound);
	FMOD_RESULT F_API getSubSound(int index, Sound** subsound);
	FMOD_RESULT F_API setSubSoundSentence(int* subsoundlist, int numsubsounds);
	FMOD_RESULT F_API getName(char* name, int namelen);
	FMOD_RESULT F_API getLength(unsigned int* length, FMOD_TIMEUNIT lengthtype);
	FMOD_RESULT F_API getFormat(FMOD_SOUND_TYPE* type, FMOD_SOUND_FORMAT* format, int* channels, int* bits);
	FMOD_RESULT F_API getNumSubSounds(int* numsubsounds);
	FMOD_RESULT F_API getNumTags(int* numtags, int* numtagsupdated);
	FMOD_RESULT F_API getTag(const char* name, int index, FMOD_TAG* tag);
	FMOD_RESULT F_API getOpenState(FMOD_OPENSTATE* openstate, unsigned int* percentbuffered, bool* starving);
	FMOD_RESULT F_API readData(void* buffer, unsigned int lenbytes, unsigned int* read);
	FMOD_RESULT F_API seekData(unsigned int pcm);

	FMOD_RESULT F_API setSoundGroup(SoundGroup* soundgroup);
	FMOD_RESULT F_API getSoundGroup(SoundGroup** soundgroup);

	FMOD_RESULT F_API getNumSyncPoints(int* numsyncpoints);
	FMOD_RESULT F_API getSyncPoint(int index, FMOD_SYNCPOINT** point);
	FMOD_RESULT F_API getSyncPointInfo(FMOD_SYNCPOINT* point, char* name, int namelen, unsigned int* offset,
	                                   FMOD_TIMEUNIT offsettype);
	FMOD_RESULT F_API addSyncPoint(unsigned int offset, FMOD_TIMEUNIT offsettype, const char* name,
	                               FMOD_SYNCPOINT** point);
	FMOD_RESULT F_API deleteSyncPoint(FMOD_SYNCPOINT* point);

	FMOD_RESULT F_API setMode(FMOD_MODE mode);
	FMOD_RESULT F_API getMode(FMOD_MODE* mode);
	FMOD_RESULT F_API setLoopCount(int loopcount);
	FMOD_RESULT F_API getLoopCount(int* loopcount);
	FMOD_RESULT F_API setLoopPoints(unsigned int loopstart, FMOD_TIMEUNIT loopstarttype, unsigned int loopend,
	                                FMOD_TIMEUNIT loopendtype);
	FMOD_RESULT F_API getLoopPoints(unsigned int* loopstart, FMOD_TIMEUNIT loopstarttype, unsigned int* loopend,
	                                FMOD_TIMEUNIT loopendtype);

	FMOD_RESULT F_API getMusicNumChannels(int* numchannels);
	FMOD_RESULT F_API setMusicChannelVolume(int channel, float volume);
	FMOD_RESULT F_API getMusicChannelVolume(int channel, float* volume);

	FMOD_RESULT F_API setUserData(void* userdata);
	FMOD_RESULT F_API getUserData(void** userdata);
};

class Channel
{
private:
	Channel();

public:
	FMOD_RESULT F_API getSystemObject(System** system);

	FMOD_RESULT F_API stop();
	FMOD_RESULT F_API setPaused(bool paused);
	FMOD_RESULT F_API getPaused(bool* paused);
	FMOD_RESULT F_API setVolume(float volume);
	FMOD_RESULT F_API getVolume(float* volume);
	FMOD_RESULT F_API setFrequency(float frequency);
	FMOD_RESULT F_API getFrequency(float* frequency);
	FMOD_RESULT F_API setPan(float pan);
	FMOD_RESULT F_API getPan(float* pan);
	FMOD_RESULT F_API setDelay(FMOD_DELAYTYPE delaytype, unsigned int delayhi, unsigned int delaylo);
	FMOD_RESULT F_API getDelay(FMOD_DELAYTYPE delaytype, unsigned int* delayhi, unsigned int* delaylo);
	FMOD_RESULT F_API setSpeakerMix(float frontleft, float frontright, float center, float lfe, float backleft,
	                                float backright, float sideleft, float sideright);
	FMOD_RESULT F_API getSpeakerMix(float* frontleft, float* frontright, float* center, float* lfe, float* backleft,
	                                float* backright, float* sideleft, float* sideright);
	FMOD_RESULT F_API setSpeakerLevels(FMOD_SPEAKER speaker, float* levels, int numlevels);
	FMOD_RESULT F_API getSpeakerLevels(FMOD_SPEAKER speaker, float* levels, int numlevels);
	FMOD_RESULT F_API setInputChannelMix(float* levels, int numlevels);
	FMOD_RESULT F_API getInputChannelMix(float* levels, int numlevels);
	FMOD_RESULT F_API setMute(bool mute);
	FMOD_RESULT F_API getMute(bool* mute);
	FMOD_RESULT F_API setPriority(int priority);
	FMOD_RESULT F_API getPriority(int* priority);
	FMOD_RESULT F_API setPosition(unsigned int position, FMOD_TIMEUNIT postype);
	FMOD_RESULT F_API getPosition(unsigned int* position, FMOD_TIMEUNIT postype);
	FMOD_RESULT F_API setReverbProperties(const FMOD_REVERB_CHANNELPROPERTIES* prop);
	FMOD_RESULT F_API getReverbProperties(FMOD_REVERB_CHANNELPROPERTIES* prop);

	FMOD_RESULT F_API setChannelGroup(ChannelGroup* channelgroup);
	FMOD_RESULT F_API getChannelGroup(ChannelGroup** channelgroup);
	FMOD_RESULT F_API setCallback(FMOD_CHANNEL_CALLBACKTYPE type, FMOD_CHANNEL_CALLBACK callback, int command);

	FMOD_RESULT F_API set3DAttributes(const FMOD_VECTOR* pos, const FMOD_VECTOR* vel);
	FMOD_RESULT F_API get3DAttributes(FMOD_VECTOR* pos, FMOD_VECTOR* vel);
	FMOD_RESULT F_API set3DMinMaxDistance(float mindistance, float maxdistance);
	FMOD_RESULT F_API get3DMinMaxDistance(float* mindistance, float* maxdistance);
	FMOD_RESULT F_API set3DConeSettings(float insideconeangle, float outsideconeangle, float outsidevolume);
	FMOD_RESULT F_API get3DConeSettings(float* insideconeangle, float* outsideconeangle, float* outsidevolume);
	FMOD_RESULT F_API set3DConeOrientation(FMOD_VECTOR* orientation);
	FMOD_RESULT F_API get3DConeOrientation(FMOD_VECTOR* orientation);
	FMOD_RESULT F_API set3DCustomRolloff(FMOD_VECTOR* points, int numpoints);
	FMOD_RESULT F_API get3DCustomRolloff(FMOD_VECTOR** points, int* numpoints);
	FMOD_RESULT F_API set3DOcclusion(float directocclusion, float reverbocclusion);
	FMOD_RESULT F_API get3DOcclusion(float* directocclusion, float* reverbocclusion);
	FMOD_RESULT F_API set3DSpread(float angle);
	FMOD_RESULT F_API get3DSpread(float* angle);
	FMOD_RESULT F_API set3DPanLevel(float level);
	FMOD_RESULT F_API get3DPanLevel(float* level);
	FMOD_RESULT F_API set3DDopplerLevel(float level);
	FMOD_RESULT F_API get3DDopplerLevel(float* level);

	FMOD_RESULT F_API getDSPHead(DSP** dsp);
	FMOD_RESULT F_API addDSP(DSP* dsp, DSPConnection** connection);

	FMOD_RESULT F_API isPlaying(bool* isplaying);
	FMOD_RESULT F_API isVirtual(bool* isvirtual);
	FMOD_RESULT F_API getAudibility(float* audibility);
	FMOD_RESULT F_API getCurrentSound(Sound** sound);
	FMOD_RESULT F_API getSpectrum(float* spectrumarray, int numvalues, int channeloffset,
	                              FMOD_DSP_FFT_WINDOW windowtype);
	FMOD_RESULT F_API getWaveData(float* wavearray, int numvalues, int channeloffset);
	FMOD_RESULT F_API getIndex(int* index);

	FMOD_RESULT F_API setMode(FMOD_MODE mode);
	FMOD_RESULT F_API getMode(FMOD_MODE* mode);
	FMOD_RESULT F_API setLoopCount(int loopcount);
	FMOD_RESULT F_API getLoopCount(int* loopcount);
	FMOD_RESULT F_API setLoopPoints(unsigned int loopstart, FMOD_TIMEUNIT loopstarttype, unsigned int loopend,
	                                FMOD_TIMEUNIT loopendtype);
	FMOD_RESULT F_API getLoopPoints(unsigned int* loopstart, FMOD_TIMEUNIT loopstarttype, unsigned int* loopend,
	                                FMOD_TIMEUNIT loopendtype);

	FMOD_RESULT F_API setUserData(void* userdata);
	FMOD_RESULT F_API getUserData(void** userdata);
};

class ChannelGroup
{
private:
	ChannelGroup();

public:
	FMOD_RESULT F_API release();
	FMOD_RESULT F_API getSystemObject(System** system);

	FMOD_RESULT F_API setVolume(float volume);
	FMOD_RESULT F_API getVolume(float* volume);
	FMOD_RESULT F_API setPitch(float pitch);
	FMOD_RESULT F_API getPitch(float* pitch);
	FMOD_RESULT F_API set3DOcclusion(float directocclusion, float reverbocclusion);
	FMOD_RESULT F_API get3DOcclusion(float* directocclusion, float* reverbocclusion);
	FMOD_RESULT F_API setPaused(bool paused);
	FMOD_RESULT F_API getPaused(bool* paused);
	FMOD_RESULT F_API setMute(bool mute);
	FMOD_RESULT F_API getMute(bool* mute);

	FMOD_RESULT F_API stop();
	FMOD_RESULT F_API overrideVolume(float volume);
	FMOD_RESULT F_API overrideFrequency(float frequency);
	FMOD_RESULT F_API overridePan(float pan);
	FMOD_RESULT F_API overrideReverbProperties(const FMOD_REVERB_CHANNELPROPERTIES* prop);
	FMOD_RESULT F_API override3DAttributes(const FMOD_VECTOR* pos, const FMOD_VECTOR* vel);
	FMOD_RESULT F_API overrideSpeakerMix(float frontleft, float frontright, float center, float lfe, float backleft,
	                                     float backright, float sideleft, float sideright);

	FMOD_RESULT F_API addGroup(ChannelGroup* group);
	FMOD_RESULT F_API getNumGroups(int* numgroups);
	FMOD_RESULT F_API getGroup(int index, ChannelGroup** group);
	FMOD_RESULT F_API getParentGroup(ChannelGroup** group);

	FMOD_RESULT F_API getDSPHead(DSP** dsp);
	FMOD_RESULT F_API addDSP(DSP* dsp, DSPConnection** connection);

	FMOD_RESULT F_API getName(char* name, int namelen);
	FMOD_RESULT F_API getNumChannels(int* numchannels);
	FMOD_RESULT F_API getChannel(int index, Channel** channel);
	FMOD_RESULT F_API getSpectrum(float* spectrumarray, int numvalues, int channeloffset,
	                              FMOD_DSP_FFT_WINDOW windowtype);
	FMOD_RESULT F_API getWaveData(float* wavearray, int numvalues, int channeloffset);

	FMOD_RESULT F_API setUserData(void* userdata);
	FMOD_RESULT F_API getUserData(void** userdata);
};

class SoundGroup
{
private:
	SoundGroup();

public:
	FMOD_RESULT F_API release();
	FMOD_RESULT F_API getSystemObject(System** system);

	FMOD_RESULT F_API setMaxAudible(int maxaudible);
	FMOD_RESULT F_API getMaxAudible(int* maxaudible);
	FMOD_RESULT F_API setMaxAudibleBehavior(FMOD_SOUNDGROUP_BEHAVIOR behavior);
	FMOD_RESULT F_API getMaxAudibleBehavior(FMOD_SOUNDGROUP_BEHAVIOR* behavior);
	FMOD_RESULT F_API setMuteFadeSpeed(float speed);
	FMOD_RESULT F_API getMuteFadeSpeed(float* speed);
	FMOD_RESULT F_API setVolume(float volume);
	FMOD_RESULT F_API getVolume(float* volume);
	FMOD_RESULT F_API stop();

	FMOD_RESULT F_API getName(char* name, int namelen);
	FMOD_RESULT F_API getNumSounds(int* numsounds);
	FMOD_RESULT F_API getSound(int index, Sound** sound);
	FMOD_RESULT F_API getNumPlaying(int* numplaying);

	FMOD_RESULT F_API setUserData(void* userdata);
	FMOD_RESULT F_API getUserData(void** userdata);
};

class DSP
{
private:
	DSP();

public:
	FMOD_RESULT F_API release();
	FMOD_RESULT F_API getSystemObject(System** system);

	FMOD_RESULT F_API addInput(DSP* target, DSPConnection** connection);
	FMOD_RESULT F_API disconnectFrom(DSP* target);
	FMOD_RESULT F_API disconnectAll(bool inputs, bool outputs);
	FMOD_RESULT F_API remove();
	FMOD_RESULT F_API getNumInputs(int* numinputs);
	FMOD_RESULT F_API getNumOutputs(int* numoutputs);
	FMOD_RESULT F_API getInput(int index, DSP** input, DSPConnection** inputconnection);
	FMOD_RESULT F_API getOutput(int index, DSP** output, DSPConnection** outputconnection);

	FMOD_RESULT F_API setActive(bool active);
	FMOD_RESULT F_API getActive(bool* active);
	FMOD_RESULT F_API setBypass(bool bypass);
	FMOD_RESULT F_API getBypass(bool* bypass);
	FMOD_RESULT F_API reset();

	FMOD_RESULT F_API setParameter(int index, float value);
	FMOD_RESULT F_API getParameter(int index, float* value, char* valuestr, int valuestrlen);
	FMOD_RESULT F_API getNumParameters(int* numparams);
	FMOD_RESULT F_API getParameterInfo(int index, char* name, char* label, char* description, int descriptionlen,
	                                   float* min, float* max);
	FMOD_RESULT F_API showConfigDialog(void* hwnd, bool show);

	FMOD_RESULT F_API getInfo(char* name, unsigned int* version, int* channels, int* configwidth,
	                          int* configheight);
	FMOD_RESULT F_API getType(FMOD_DSP_TYPE* type);
	FMOD_RESULT F_API setDefaults(float frequency, float volume, float pan, int priority);
	FMOD_RESULT F_API getDefaults(float* frequency, float* volume, float* pan, int* priority);

	FMOD_RESULT F_API setUserData(void* userdata);
	FMOD_RESULT F_API getUserData(void** userdata);
};

class DSPConnection
{
private:
	DSPConnection();

public:
	FMOD_RESULT F_API getInput(DSP** input);
	FMOD_RESULT F_API getOutput(DSP** output);
	FMOD_RESULT F_API setMix(float volume);
	FMOD_RESULT F_API getMix(float* volume);
	FMOD_RESULT F_API setLevels(FMOD_SPEAKER speaker, float* levels, int numlevels);
	FMOD_RESULT F_API getLevels(FMOD_SPEAKER speaker, float* levels, int numlevels);

	FMOD_RESULT F_API setUserData(void* userdata);
	FMOD_RESULT F_API getUserData(void** userdata);
};

class Geometry
{
private:
	Geometry();

public:
	FMOD_RESULT F_API release();

	FMOD_RESULT F_API addPolygon(float directocclusion, float reverbocclusion, bool doublesided, int numvertices,
	                             const FMOD_VECTOR* vertices, int* polygonindex);
	FMOD_RESULT F_API getNumPolygons(int* numpolygons);
	FMOD_RESULT F_API getMaxPolygons(int* maxpolygons, int* maxvertices);
	FMOD_RESULT F_API getPolygonNumVertices(int index, int* numvertices);
	FMOD_RESULT F_API setPolygonVertex(int index, int vertexindex, const FMOD_VECTOR* vertex);
	FMOD_RESULT F_API getPolygonVertex(int index, int vertexindex, FMOD_VECTOR* vertex);
	FMOD_RESULT F_API setPolygonAttributes(int index, float directocclusion, float reverbocclusion,
	                                       bool doublesided);
	FMOD_RESULT F_API getPolygonAttributes(int index, float* directocclusion, float* reverbocclusion,
	                                       bool* doublesided);

	FMOD_RESULT F_API setActive(bool active);
	FMOD_RESULT F_API getActive(bool* active);
	FMOD_RESULT F_API setRotation(const FMOD_VECTOR* forward, const FMOD_VECTOR* up);
	FMOD_RESULT F_API getRotation(FMOD_VECTOR* forward, FMOD_VECTOR* up);
	FMOD_RESULT F_API setPosition(const FMOD_VECTOR* position);
	FMOD_RESULT F_API getPosition(FMOD_VECTOR* position);
	FMOD_RESULT F_API setScale(const FMOD_VECTOR* scale);
	FMOD_RESULT F_API getScale(FMOD_VECTOR* scale);
	FMOD_RESULT F_API save(void* data, int* datasize);

	FMOD_RESULT F_API setUserData(void* userdata);
	FMOD_RESULT F_API getUserData(void** userdata);
};

class Reverb
{
private:
	Reverb();

public:
	FMOD_RESULT F_API release();

	FMOD_RESULT F_API set3DAttributes(const FMOD_VECTOR* position, float mindistance, float maxdistance);
	FMOD_RESULT F_API get3DAttributes(FMOD_VECTOR* position, float* mindistance, float* maxdistance);
	FMOD_RESULT F_API setProperties(const FMOD_REVERB_PROPERTIES* properties);
	FMOD_RESULT F_API getProperties(FMOD_REVERB_PROPERTIES* properties);
	FMOD_RESULT F_API setActive(bool active);
	FMOD_RESULT F_API getActive(bool* active);

	FMOD_RESULT F_API setUserData(void* userdata);
	FMOD_RESULT F_API getUserData(void** userdata);
};

class EventSystem;
class EventCategory;
class EventProject;
class EventGroup;
class Event;
class EventParameter;
class EventReverb;
class MusicSystem;

FMOD_RESULT EventSystem_Create(EventSystem** eventsystem);

// CryMP: for old FMOD
class EventSystemOld
{
public:
	virtual FMOD_RESULT F_API init(int maxchannels, FMOD_INITFLAGS flags, void* extradriverdata,
	                               FMOD_EVENT_INITFLAGS eventflags = FMOD_EVENT_INIT_NORMAL) = 0;
	virtual FMOD_RESULT F_API release() = 0;
	virtual FMOD_RESULT F_API update() = 0;
	virtual FMOD_RESULT F_API setMediaPath(const char* path) = 0;
	virtual FMOD_RESULT F_API setPluginPath(const char* path) = 0;
	virtual FMOD_RESULT F_API getVersion(unsigned int* version) = 0;
	virtual FMOD_RESULT F_API getInfo(FMOD_EVENT_SYSTEMINFO* info) = 0;
	virtual FMOD_RESULT F_API getSystemObject(System** system) = 0;

	virtual FMOD_RESULT F_API load(const char* name_or_data, FMOD_EVENT_LOADINFO* loadinfo,
	                               EventProject** project) = 0;
	virtual FMOD_RESULT F_API unload() = 0;

	virtual FMOD_RESULT F_API getProject(const char* name, EventProject** project) = 0;
	virtual FMOD_RESULT F_API getProjectByIndex(int index, EventProject** project) = 0;
	virtual FMOD_RESULT F_API getNumProjects(int* numprojects) = 0;
	virtual FMOD_RESULT F_API getCategory(const char* name, EventCategory** category) = 0;
	virtual FMOD_RESULT F_API getCategoryByIndex(int index, EventCategory** category) = 0;
	virtual FMOD_RESULT F_API getNumCategories(int* numcategories) = 0;
	virtual FMOD_RESULT F_API getGroup(const char* name, bool cacheevents, EventGroup** group) = 0;
	virtual FMOD_RESULT F_API getEvent(const char* name, FMOD_EVENT_MODE mode, Event** event) = 0;
	virtual FMOD_RESULT F_API getEventBySystemID(unsigned int systemid, FMOD_EVENT_MODE mode, Event** event) = 0;
	virtual FMOD_RESULT F_API getNumEvents(int* numevents) = 0;

	virtual FMOD_RESULT F_API setReverbProperties(const FMOD_REVERB_PROPERTIES* prop) = 0;
	virtual FMOD_RESULT F_API getReverbProperties(FMOD_REVERB_PROPERTIES* prop) = 0;

	virtual FMOD_RESULT F_API getReverbPreset(const char* name, FMOD_REVERB_PROPERTIES* prop, int* index = 0) = 0;
	virtual FMOD_RESULT F_API getReverbPresetByIndex(const int index, FMOD_REVERB_PROPERTIES* prop,
	                                                 char** name = 0) = 0;
	virtual FMOD_RESULT F_API getNumReverbPresets(int* numpresets) = 0;

	virtual FMOD_RESULT F_API createReverb(EventReverb** reverb) = 0;
	virtual FMOD_RESULT F_API setReverbAmbientProperties(FMOD_REVERB_PROPERTIES* prop) = 0;
	virtual FMOD_RESULT F_API getReverbAmbientProperties(FMOD_REVERB_PROPERTIES* prop) = 0;

	virtual FMOD_RESULT F_API set3DNumListeners(int numlisteners) = 0;
	virtual FMOD_RESULT F_API get3DNumListeners(int* numlisteners) = 0;
	virtual FMOD_RESULT F_API set3DListenerAttributes(int listener, const FMOD_VECTOR* pos, const FMOD_VECTOR* vel,
	                                                  const FMOD_VECTOR* forward, const FMOD_VECTOR* up) = 0;
	virtual FMOD_RESULT F_API get3DListenerAttributes(int listener, FMOD_VECTOR* pos, FMOD_VECTOR* vel,
	                                                  FMOD_VECTOR* forward, FMOD_VECTOR* up) = 0;

	virtual FMOD_RESULT F_API setUserData(void* userdata) = 0;
	virtual FMOD_RESULT F_API getUserData(void** userdata) = 0;

	virtual FMOD_RESULT F_API registerMemoryFSB(const char* filename, void* fsbdata, unsigned int fsbdatalen,
	                                            bool loadintorsx = false) = 0;
	virtual FMOD_RESULT F_API unregisterMemoryFSB(const char* filename) = 0;

	virtual ~EventSystemOld() {};
};

class EventSystem
{
public:
	virtual FMOD_RESULT F_API init(int maxchannels, FMOD_INITFLAGS flags, void* extradriverdata,
	                               FMOD_EVENT_INITFLAGS eventflags = FMOD_EVENT_INIT_NORMAL) = 0;
	virtual FMOD_RESULT F_API release() = 0;
	virtual FMOD_RESULT F_API update() = 0;
	virtual FMOD_RESULT F_API setMediaPath(const char* path) = 0;
	virtual FMOD_RESULT F_API setPluginPath(const char* path) = 0;
	virtual FMOD_RESULT F_API getVersion(unsigned int* version) = 0;
	virtual FMOD_RESULT F_API getInfo(FMOD_EVENT_SYSTEMINFO* info) = 0;
	virtual FMOD_RESULT F_API getSystemObject(System** system) = 0;

private:
	// CryMP: no getMusicSystem in old FMOD
	virtual FMOD_RESULT F_API getMusicSystem_(MusicSystem** musicsystem) = 0;

	virtual FMOD_RESULT F_API load_(const char* name_or_data, FMOD_EVENT_LOADINFO* loadinfo,
	                                EventProject** project) = 0;
	virtual FMOD_RESULT F_API unload_() = 0;

	virtual FMOD_RESULT F_API getProject_(const char* name, EventProject** project) = 0;
	virtual FMOD_RESULT F_API getProjectByIndex_(int index, EventProject** project) = 0;
	virtual FMOD_RESULT F_API getNumProjects_(int* numprojects) = 0;
	virtual FMOD_RESULT F_API getCategory_(const char* name, EventCategory** category) = 0;
	virtual FMOD_RESULT F_API getCategoryByIndex_(int index, EventCategory** category) = 0;
	virtual FMOD_RESULT F_API getNumCategories_(int* numcategories) = 0;
	virtual FMOD_RESULT F_API getGroup_(const char* name, bool cacheevents, EventGroup** group) = 0;
	virtual FMOD_RESULT F_API getEvent_(const char* name, FMOD_EVENT_MODE mode, Event** event) = 0;
	virtual FMOD_RESULT F_API getEventBySystemID_(unsigned int systemid, FMOD_EVENT_MODE mode, Event** event) = 0;
	virtual FMOD_RESULT F_API getNumEvents_(int* numevents) = 0;

	virtual FMOD_RESULT F_API setReverbProperties_(const FMOD_REVERB_PROPERTIES* prop) = 0;
	virtual FMOD_RESULT F_API getReverbProperties_(FMOD_REVERB_PROPERTIES* prop) = 0;

	virtual FMOD_RESULT F_API getReverbPreset_(const char* name, FMOD_REVERB_PROPERTIES* prop, int* index = 0) = 0;
	virtual FMOD_RESULT F_API getReverbPresetByIndex_(const int index, FMOD_REVERB_PROPERTIES* prop,
	                                                  char** name = 0) = 0;
	virtual FMOD_RESULT F_API getNumReverbPresets_(int* numpresets) = 0;

	virtual FMOD_RESULT F_API createReverb_(EventReverb** reverb) = 0;
	virtual FMOD_RESULT F_API setReverbAmbientProperties_(FMOD_REVERB_PROPERTIES* prop) = 0;
	virtual FMOD_RESULT F_API getReverbAmbientProperties_(FMOD_REVERB_PROPERTIES* prop) = 0;

	virtual FMOD_RESULT F_API set3DNumListeners_(int numlisteners) = 0;
	virtual FMOD_RESULT F_API get3DNumListeners_(int* numlisteners) = 0;
	virtual FMOD_RESULT F_API set3DListenerAttributes_(int listener, const FMOD_VECTOR* pos, const FMOD_VECTOR* vel,
	                                                   const FMOD_VECTOR* forward, const FMOD_VECTOR* up) = 0;
	virtual FMOD_RESULT F_API get3DListenerAttributes_(int listener, FMOD_VECTOR* pos, FMOD_VECTOR* vel,
	                                                   FMOD_VECTOR* forward, FMOD_VECTOR* up) = 0;

	virtual FMOD_RESULT F_API setUserData_(void* userdata) = 0;
	virtual FMOD_RESULT F_API getUserData_(void** userdata) = 0;

	virtual FMOD_RESULT F_API registerMemoryFSB_(const char* filename, void* fsbdata, unsigned int fsbdatalen,
	                                             bool loadintorsx = false) = 0;
	virtual FMOD_RESULT F_API unregisterMemoryFSB_(const char* filename) = 0;

	virtual ~EventSystem() {};

public:
	FMOD_RESULT load(const char* name_or_data, FMOD_EVENT_LOADINFO* loadinfo, EventProject** project)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->load(name_or_data, loadinfo, project);
		}

		return this->load_(name_or_data, loadinfo, project);
	}

	FMOD_RESULT unload()
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->unload();
		}

		return this->unload_();
	}

	FMOD_RESULT getProject(const char* name, EventProject** project)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->getProject(name, project);
		}

		return this->getProject_(name, project);
	}

	FMOD_RESULT getProjectByIndex(int index, EventProject** project)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->getProjectByIndex(index, project);
		}

		return this->getProjectByIndex_(index, project);
	}

	FMOD_RESULT getNumProjects(int* numprojects)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->getNumProjects(numprojects);
		}

		return this->getNumProjects_(numprojects);
	}

	FMOD_RESULT getCategory(const char* name, EventCategory** category)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->getCategory(name, category);
		}

		return this->getCategory_(name, category);
	}

	FMOD_RESULT getCategoryByIndex(int index, EventCategory** category)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->getCategoryByIndex(index, category);
		}

		return this->getCategoryByIndex_(index, category);
	}

	FMOD_RESULT getNumCategories(int* numcategories)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->getNumCategories(numcategories);
		}

		return this->getNumCategories_(numcategories);
	}

	FMOD_RESULT getGroup(const char* name, bool cacheevents, EventGroup** group)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->getGroup(name, cacheevents, group);
		}

		return this->getGroup_(name, cacheevents, group);
	}

	FMOD_RESULT getEvent(const char* name, FMOD_EVENT_MODE mode, Event** event)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->getEvent(name, mode, event);
		}

		return this->getEvent_(name, mode, event);
	}

	FMOD_RESULT getEventBySystemID(unsigned int systemid, FMOD_EVENT_MODE mode, Event** event)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->getEventBySystemID(systemid, mode, event);
		}

		return this->getEventBySystemID_(systemid, mode, event);
	}

	FMOD_RESULT getNumEvents(int* numevents)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->getNumEvents(numevents);
		}

		return this->getNumEvents_(numevents);
	}

	FMOD_RESULT setReverbProperties(const FMOD_REVERB_PROPERTIES* prop)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->setReverbProperties(prop);
		}

		return this->setReverbProperties_(prop);
	}

	FMOD_RESULT getReverbProperties(FMOD_REVERB_PROPERTIES* prop)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->getReverbProperties(prop);
		}

		return this->getReverbProperties_(prop);
	}

	FMOD_RESULT getReverbPreset(const char* name, FMOD_REVERB_PROPERTIES* prop, int* index = 0)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->getReverbPreset(name, prop, index);
		}

		return this->getReverbPreset_(name, prop, index);
	}

	FMOD_RESULT getReverbPresetByIndex(const int index, FMOD_REVERB_PROPERTIES* prop, char** name = 0)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->getReverbPresetByIndex(index, prop, name);
		}

		return this->getReverbPresetByIndex_(index, prop, name);
	}

	FMOD_RESULT getNumReverbPresets(int* numpresets)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->getNumReverbPresets(numpresets);
		}

		return this->getNumReverbPresets_(numpresets);
	}

	FMOD_RESULT createReverb(EventReverb** reverb)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->createReverb(reverb);
		}

		return this->createReverb_(reverb);
	}

	FMOD_RESULT setReverbAmbientProperties(FMOD_REVERB_PROPERTIES* prop)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->setReverbAmbientProperties(prop);
		}

		return this->setReverbAmbientProperties_(prop);
	}

	FMOD_RESULT getReverbAmbientProperties(FMOD_REVERB_PROPERTIES* prop)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->getReverbAmbientProperties(prop);
		}

		return this->getReverbAmbientProperties_(prop);
	}

	FMOD_RESULT set3DNumListeners(int numlisteners)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->set3DNumListeners(numlisteners);
		}

		return this->set3DNumListeners_(numlisteners);
	}

	FMOD_RESULT get3DNumListeners(int* numlisteners)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->get3DNumListeners(numlisteners);
		}

		return this->get3DNumListeners_(numlisteners);
	}

	FMOD_RESULT set3DListenerAttributes(int listener, const FMOD_VECTOR* pos, const FMOD_VECTOR* vel,
	                                    const FMOD_VECTOR* forward, const FMOD_VECTOR* up)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->set3DListenerAttributes(listener, pos, vel,
			                                                                        forward, up);
		}

		return this->set3DListenerAttributes_(listener, pos, vel, forward, up);
	}

	FMOD_RESULT get3DListenerAttributes(int listener, FMOD_VECTOR* pos, FMOD_VECTOR* vel, FMOD_VECTOR* forward,
	                                    FMOD_VECTOR* up)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->get3DListenerAttributes(listener, pos, vel,
			                                                                        forward, up);
		}

		return this->get3DListenerAttributes_(listener, pos, vel, forward, up);
	}

	FMOD_RESULT setUserData(void* userdata)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->setUserData(userdata);
		}

		return this->setUserData_(userdata);
	}

	FMOD_RESULT getUserData(void** userdata)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->getUserData(userdata);
		}

		return this->getUserData_(userdata);
	}

	FMOD_RESULT registerMemoryFSB(const char* filename, void* fsbdata, unsigned int fsbdatalen,
	                              bool loadintorsx = false)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->registerMemoryFSB(filename, fsbdata, fsbdatalen,
			                                                                  loadintorsx);
		}

		return this->registerMemoryFSB_(filename, fsbdata, fsbdatalen, loadintorsx);
	}

	FMOD_RESULT unregisterMemoryFSB(const char* filename)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventSystemOld*>(this)->unregisterMemoryFSB(filename);
		}

		return this->unregisterMemoryFSB_(filename);
	}
};

class EventProject
{
public:
	virtual FMOD_RESULT F_API release() = 0;
	virtual FMOD_RESULT F_API getInfo(int* index, char** name) = 0;
	virtual FMOD_RESULT F_API getGroup(const char* name, bool cacheevents, EventGroup** group) = 0;
	virtual FMOD_RESULT F_API getGroupByIndex(int index, bool cacheevents, EventGroup** group) = 0;
	virtual FMOD_RESULT F_API getNumGroups(int* numgroups) = 0;
	virtual FMOD_RESULT F_API getEvent(const char* name, FMOD_EVENT_MODE mode, Event** event) = 0;
	virtual FMOD_RESULT F_API getEventByProjectID(unsigned int projectid, FMOD_EVENT_MODE mode, Event** event) = 0;
	virtual FMOD_RESULT F_API getNumEvents(int* numevents) = 0;
	virtual FMOD_RESULT F_API setUserData(void* userdata) = 0;
	virtual FMOD_RESULT F_API getUserData(void** userdata) = 0;

	virtual ~EventProject() {};
};

class EventGroup
{
public:
	virtual FMOD_RESULT F_API getInfo(int* index, char** name) = 0;
	virtual FMOD_RESULT F_API loadEventData(FMOD_EVENT_RESOURCE resource = FMOD_EVENT_RESOURCE_STREAMS_AND_SAMPLES,
	                                        FMOD_EVENT_MODE mode = FMOD_EVENT_DEFAULT) = 0;
	virtual FMOD_RESULT F_API freeEventData(Event* event = 0, bool waituntilready = true) = 0;
	virtual FMOD_RESULT F_API getGroup(const char* name, bool cacheevents, EventGroup** group) = 0;
	virtual FMOD_RESULT F_API getGroupByIndex(int index, bool cacheevents, EventGroup** group) = 0;
	virtual FMOD_RESULT F_API getParentGroup(EventGroup** group) = 0;
	virtual FMOD_RESULT F_API getParentProject(EventProject** project) = 0;
	virtual FMOD_RESULT F_API getNumGroups(int* numgroups) = 0;
	virtual FMOD_RESULT F_API getEvent(const char* name, FMOD_EVENT_MODE mode, Event** event) = 0;
	virtual FMOD_RESULT F_API getEventByIndex(int index, FMOD_EVENT_MODE mode, Event** event) = 0;
	virtual FMOD_RESULT F_API getNumEvents(int* numevents) = 0;
	virtual FMOD_RESULT F_API getProperty(const char* propertyname, void* value) = 0;

private:
	virtual FMOD_RESULT F_API getPropertyByIndex_(int propertyindex, void* value) = 0;

public:
	virtual FMOD_RESULT F_API getNumProperties(int* numproperties) = 0;
	virtual FMOD_RESULT F_API getState(FMOD_EVENT_STATE* state) = 0;
	virtual FMOD_RESULT F_API setUserData(void* userdata) = 0;
	virtual FMOD_RESULT F_API getUserData(void** userdata) = 0;

	virtual ~EventGroup() {};

	FMOD_RESULT getPropertyByIndex(int propertyindex, void* value)
	{
		if (g_hasC1Fmod)
		{
			propertyindex = AdjustEventPropertyForOldFmod(propertyindex);
			if (propertyindex < 0)
			{
				return FMOD_ERR_INVALID_PARAM;
			}
		}

		return this->getPropertyByIndex_(propertyindex, value);
	}
};

// CryMP: for old FMOD
class EventCategoryOld
{
public:
	virtual FMOD_RESULT F_API getInfo(int* index, char** name) = 0;
	virtual FMOD_RESULT F_API getCategory(const char* name, EventCategory** category) = 0;
	virtual FMOD_RESULT F_API getCategoryByIndex(int index, EventCategory** category) = 0;
	virtual FMOD_RESULT F_API getNumCategories(int* numcategories) = 0;
	virtual FMOD_RESULT F_API getEventByIndex(int index, FMOD_EVENT_MODE mode, Event** event) = 0;
	virtual FMOD_RESULT F_API getNumEvents(int* numevents) = 0;

	virtual FMOD_RESULT F_API stopAllEvents() = 0;
	virtual FMOD_RESULT F_API setVolume(float volume) = 0;
	virtual FMOD_RESULT F_API getVolume(float* volume) = 0;
	virtual FMOD_RESULT F_API setPitch(float pitch) = 0;
	virtual FMOD_RESULT F_API getPitch(float* pitch) = 0;
	virtual FMOD_RESULT F_API setPaused(bool paused) = 0;
	virtual FMOD_RESULT F_API getPaused(bool* paused) = 0;
	virtual FMOD_RESULT F_API setMute(bool mute) = 0;
	virtual FMOD_RESULT F_API getMute(bool* mute) = 0;
	virtual FMOD_RESULT F_API getChannelGroup(ChannelGroup** channelgroup) = 0;
	virtual FMOD_RESULT F_API setUserData(void* userdata) = 0;
	virtual FMOD_RESULT F_API getUserData(void** userdata) = 0;

	virtual ~EventCategoryOld() {};
};

class EventCategory
{
public:
	virtual FMOD_RESULT F_API getInfo(int* index, char** name) = 0;
	virtual FMOD_RESULT F_API getCategory(const char* name, EventCategory** category) = 0;
	virtual FMOD_RESULT F_API getCategoryByIndex(int index, EventCategory** category) = 0;
	virtual FMOD_RESULT F_API getNumCategories(int* numcategories) = 0;
	virtual FMOD_RESULT F_API getEventByIndex(int index, FMOD_EVENT_MODE mode, Event** event) = 0;
	virtual FMOD_RESULT F_API getNumEvents(int* numevents) = 0;

	virtual FMOD_RESULT F_API stopAllEvents() = 0;
	virtual FMOD_RESULT F_API setVolume(float volume) = 0;
	virtual FMOD_RESULT F_API getVolume(float* volume) = 0;

private:
	// CryMP: no units parameter in old FMOD
	virtual FMOD_RESULT F_API setPitch_(float pitch, FMOD_EVENT_PITCHUNITS units = FMOD_EVENT_PITCHUNITS_RAW) = 0;
	// CryMP: no units parameter in old FMOD
	virtual FMOD_RESULT F_API getPitch_(float* pitch, FMOD_EVENT_PITCHUNITS units = FMOD_EVENT_PITCHUNITS_RAW) = 0;

public:
	virtual FMOD_RESULT F_API setPaused(bool paused) = 0;
	virtual FMOD_RESULT F_API getPaused(bool* paused) = 0;
	virtual FMOD_RESULT F_API setMute(bool mute) = 0;
	virtual FMOD_RESULT F_API getMute(bool* mute) = 0;
	virtual FMOD_RESULT F_API getChannelGroup(ChannelGroup** channelgroup) = 0;
	virtual FMOD_RESULT F_API setUserData(void* userdata) = 0;
	virtual FMOD_RESULT F_API getUserData(void** userdata) = 0;

	virtual ~EventCategory() {};

	FMOD_RESULT setPitch(float pitch, FMOD_EVENT_PITCHUNITS units = FMOD_EVENT_PITCHUNITS_RAW)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventCategoryOld*>(this)->setPitch(pitch);
		}

		return this->setPitch_(pitch, units);
	}

	FMOD_RESULT getPitch(float* pitch, FMOD_EVENT_PITCHUNITS units = FMOD_EVENT_PITCHUNITS_RAW)
	{
		if (g_hasC1Fmod)
		{
			return reinterpret_cast<EventCategoryOld*>(this)->getPitch(pitch);
		}

		return this->getPitch_(pitch, units);
	}
};

class Event
{
public:
	FMOD_RESULT F_API start();
	FMOD_RESULT F_API stop(bool immediate = false);

	FMOD_RESULT F_API getInfo(int* index, char** name, FMOD_EVENT_INFO* info);
	FMOD_RESULT F_API getState(FMOD_EVENT_STATE* state);
	FMOD_RESULT F_API getParentGroup(EventGroup** group);
	FMOD_RESULT F_API getChannelGroup(ChannelGroup** channelgroup);
	FMOD_RESULT F_API setCallback(FMOD_EVENT_CALLBACK callback, void* userdata);

	FMOD_RESULT F_API getParameter(const char* name, EventParameter** parameter);
	FMOD_RESULT F_API getParameterByIndex(int index, EventParameter** parameter);
	FMOD_RESULT F_API getNumParameters(int* numparameters);
	FMOD_RESULT F_API getProperty(const char* propertyname, void* value, bool this_instance = false);
	FMOD_RESULT F_API getPropertyByIndex(int propertyindex, void* value, bool this_instance = false);
	FMOD_RESULT F_API setProperty(const char* propertyname, void* value, bool this_instance = false);
	FMOD_RESULT F_API setPropertyByIndex(int propertyindex, void* value, bool this_instance = false);
	FMOD_RESULT F_API getNumProperties(int* numproperties);
	FMOD_RESULT F_API getCategory(EventCategory** category);

	FMOD_RESULT F_API setVolume(float volume);
	FMOD_RESULT F_API getVolume(float* volume);
	FMOD_RESULT F_API setPitch(float pitch, FMOD_EVENT_PITCHUNITS units = FMOD_EVENT_PITCHUNITS_RAW);
	FMOD_RESULT F_API getPitch(float* pitch, FMOD_EVENT_PITCHUNITS units = FMOD_EVENT_PITCHUNITS_RAW);
	FMOD_RESULT F_API setPaused(bool paused);
	FMOD_RESULT F_API getPaused(bool* paused);
	FMOD_RESULT F_API setMute(bool mute);
	FMOD_RESULT F_API getMute(bool* mute);
	FMOD_RESULT F_API set3DAttributes(const FMOD_VECTOR* position, const FMOD_VECTOR* velocity,
	                                  const FMOD_VECTOR* orientation = 0);
	FMOD_RESULT F_API get3DAttributes(FMOD_VECTOR* position, FMOD_VECTOR* velocity, FMOD_VECTOR* orientation = 0);
	FMOD_RESULT F_API set3DOcclusion(float directocclusion, float reverbocclusion);
	FMOD_RESULT F_API get3DOcclusion(float* directocclusion, float* reverbocclusion);
	FMOD_RESULT F_API setReverbProperties(const FMOD_REVERB_CHANNELPROPERTIES* prop);
	FMOD_RESULT F_API getReverbProperties(FMOD_REVERB_CHANNELPROPERTIES* prop);
	FMOD_RESULT F_API setUserData(void* userdata);
	FMOD_RESULT F_API getUserData(void** userdata);
};

class EventParameter
{
public:
	FMOD_RESULT F_API getInfo(int* index, char** name);
	FMOD_RESULT F_API getRange(float* rangemin, float* rangemax);
	FMOD_RESULT F_API setValue(float value);
	FMOD_RESULT F_API getValue(float* value);
	FMOD_RESULT F_API setVelocity(float value);
	FMOD_RESULT F_API getVelocity(float* value);
	FMOD_RESULT F_API setSeekSpeed(float value);
	FMOD_RESULT F_API getSeekSpeed(float* value);
	FMOD_RESULT F_API setUserData(void* userdata);
	FMOD_RESULT F_API getUserData(void** userdata);
	FMOD_RESULT F_API keyOff();
};

class EventReverb
{
public:
	virtual FMOD_RESULT F_API release() = 0;
	virtual FMOD_RESULT F_API set3DAttributes(const FMOD_VECTOR* position, float mindistance,
	                                          float maxdistance) = 0;
	virtual FMOD_RESULT F_API get3DAttributes(FMOD_VECTOR* position, float* mindistance, float* maxdistance) = 0;
	virtual FMOD_RESULT F_API setProperties(const FMOD_REVERB_PROPERTIES* props) = 0;
	virtual FMOD_RESULT F_API getProperties(FMOD_REVERB_PROPERTIES* props) = 0;
	virtual FMOD_RESULT F_API setActive(bool active) = 0;
	virtual FMOD_RESULT F_API getActive(bool* active) = 0;
	virtual FMOD_RESULT F_API setUserData(void* userdata) = 0;
	virtual FMOD_RESULT F_API getUserData(void** userdata) = 0;

	virtual ~EventReverb() {};
};

} // namespace FMOD
