################################################################################
# Create and publish a new development version from the master branch
################################################################################

name: Dev

on:
  push:
    branches:
      - master
    tags:
      # sync dev version with the official one upon release
      - v*

jobs:
  build_32:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      bits: 32
      type: RelWithDebInfo

  build_64:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      bits: 64
      type: RelWithDebInfo

  server_zip:
    uses: ./.github/workflows/server-zip.yml
    needs:
      - build_32
      - build_64
    with:
      build_artifact_32: ${{ needs.build_32.outputs.artifact_name }}
      build_artifact_64: ${{ needs.build_64.outputs.artifact_name }}

  publish:
    if: github.repository_owner == 'crymp-net'
    needs:
      - build_32
      - build_64
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      context: dev
      artifact_32: ${{ needs.build_32.outputs.artifact_name }}
      artifact_64: ${{ needs.build_64.outputs.artifact_name }}
